### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by ankitnagarsheth** [AdobeDocs/analytics.en#1]
Issue in help/implement/implement-with-launch/deploy-dev.md

On the url https://docs.adobe.com/content/help/en/analytics/implementation/implement-with-launch/deploy-dev.html 
Launch Administration: Learn more about adapters and environments is going to **Page Not Found.**

**Comment by MicaPete** [comment]
Hi Ankit - we are experiencing a number of issues with redirects, since just went live on docs.adobe.com today - please bear with us as we fix these issues.

**Comment by MicaPete** [comment]
This should be fixed now.
