### ISSUE TITLE
IS there a way to stop Activity map from firing on certain pages of Site? 

### ISSUE THREAD

**Issue by frambert** [AdobeDocs/analytics.en#100]
IS there a way to stop Activity map from firing on certain pages of Site without affecting rest of Analytics call?

**Comment by markmontymark** [comment]
ActivityMap functionality and having ActivityMap data added to an Analytics call is encapsulated by the s.ActivityMap module.  If s.ActivityMap is not loaded, or is made undefined, then that stops it.

So, ways to do that:

```javascript
s.ActivityMap = undefined;
s.ActivityMap = 0;
s.ActivityMap = null;
s.ActivityMap = false;
```

Assuming 1 of the above is added before a click event occurs, then ActivityMap won't track that page's click events.

**Comment by MicaPete** [comment]
@frambert - please let us know whether this answers your question.

**Comment by frambert** [comment]
Thanks Guys,

That helps indeed.

Much appreciated.

Will now proceed to try and leverage launch to do this on clicks on specific links.

Best



Frédérique Rambert
Senior Consultant – Technology – ENABLEMENT SERVICES, EMEA
acceleration
A WUNDERMAN THOMPSON COMPANY
 www.acceleration.biz<https://www.acceleration.biz>

3rd Floor, Greater London House
Hampstead Road
London NW1 7QP
C
T

+33 612 181 740
+44 208 132 7815
Twitter<https://twitter.com/accelerationbiz>
LinkedIn<http://www.linkedin.com/company/acceleration>
Our blog<https://www.acceleration.biz/our-thinking/>

**Comment by gigazelle** [comment]
We do not support the manipulation of the `s.ActivityMap` object. Instead, just set `s.trackInlineStats` to `false`:

https://docs.adobe.com/content/help/en/analytics/implementation/vars/config-vars/trackinlinestats.html

Also worth noting is that issues on git is typically direct improvements to docs, and not general questions. If you have these sorts of questions in the future, I would recommend filing a ticket with Customer Care.

Thanks!
