### ISSUE TITLE
Data Layer Question

### ISSUE THREAD

**Issue by thisishima9** [AdobeDocs/analytics.en#103]
Issue in help/implement/prepare/data-layer.md

Hello, 

I am developing curriculum for implementing adobe analytics. Whole going through this document, one of my SME mentioned that there is a new **Event Driven Data Layer**. I could not find any information about it on Adobe docs. I am a full time adobe employee. Who do I reach out regarding the information about Event Driven Data Layer? Please let me know. 

Regards, 
Hima Jasti

**Comment by arobsco** [comment]
@thisishima9 I think this is what you are referring to: https://github.com/adobe/adobe-client-data-layer

**Comment by MicaPete** [comment]
@thisishima9 - does Andrew's comment answer your question?
