### ISSUE TITLE
Out-of-date content in "Settings not copied from RS" article

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#112]
Issue in help/admin/c-manage-report-suites/c-new-report-suite/settings-not-copied-from-rs.md

This article appears to have some out-of-date info; for example, it claims that Success Event "Unique Recording" settings are not copied, which seems to be incorrect.

**Comment by MicaPete** [comment]
@inselaffe  - following up on this now...

**Comment by MicaPete** [comment]
Thanks @inselaffe - this has now been fixed.
