### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by lukasz-ecx** [AdobeDocs/analytics.en#113]
Issue in help/components/dimensions/evar-merchandising.md

URL in "See Merchandising eVars for implementation instructions." does not work.

**Comment by ddave2004** [comment]
Hi, I tried to fix this simple issue but this seems to be working !

**Comment by lukasz-ecx** [comment]
This link (placed on the website) returns 404 error:
https://docs.adobe.com/content/help/en/analytics/implement/vars/page-vars/evar-merchandising.md

**Comment by gigazelle** [comment]
Thanks for the report! This has been fixed, and will be published in the next day or so.
