### ISSUE TITLE
Logic Group definition

### ISSUE THREAD

**Issue by pitchmuc** [AdobeDocs/analytics.en#115]
Issue in help/components/c-segmentation/c-segmentation-workflow/seg-sequential-build.md

In the logic group definition, it is said that Logic group could help building segment for multi-conditional condition. 

Example given is : 
Do Logic Groups simplify building sequential segments? Yes, they can. Let's assume you are trying to answer this question: Did a visitor see page B, or page C, or page D after page A?

Following the example that follows :
![image](https://user-images.githubusercontent.com/32903178/85305261-1d2c3600-b4ad-11ea-9a0d-68eb44a4ab45.png)

and this one : 
![image](https://user-images.githubusercontent.com/32903178/85305311-303f0600-b4ad-11ea-8afb-cff49bb35aca.png)

I would assume that the correct statement above is : 
Do Logic Groups simplify building sequential segments? Yes, they can. Let's assume you are trying to answer this question: Did a visitor see page B, **and** page C, **and** page D after page A?

**Comment by MicaPete** [comment]
@pitchmuc - we have updated the example and it should be published by end of day (MDT).
