### ISSUE TITLE
Segment Stacking is now supported in Data Warehouse

### ISSUE THREAD

**Issue by rachelsubscribe01** [AdobeDocs/analytics.en#116]
Issue in help/components/c-segmentation/seg-reference/seg-compatibility.md

**Segment Stacking is now supported in Data Warehouse**
https://docs.adobe.com/content/help/en/analytics/components/segmentation/whats-new-segmentation.html

Data Warehouse: Segment stacking | Added support for multiple segments (segment stacking) to Data Warehouse.When selecting multiple segments, the preview area now shows a comma-separated list of names (e.g. Segment 1, Segment 2). We also updated the Request Manager page and the Request Detail popup window to display the comma-separated list.
-- | --

**Comment by MicaPete** [comment]
I have merged this change into the corp repo - it should be published by tomorrow. Thanks for noticing this error.
