### ISSUE TITLE
How to is missing

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/analytics.en#120]
Issue in help/admin/admin/internal-url-filter-admin.md

"To check which Internal URL Filters have been set up on a report suite, follow these steps. To avoid this, remove the rule listing a period (.) as a filter, and add your own site. "

The above steps are not clear as to under which navigation one need to go and change this setting.

**Comment by MicaPete** [comment]
@himanshu-pathak  - I added the navigation path and this should be published by end of day (US) today.
