### ISSUE TITLE
Left rail - Chevron icon alignment off center

### ISSUE THREAD

**Issue by bryantabaird** [AdobeDocs/analytics.en#124]
Strange alignment with the chevron icons, they don't seem to be vertically aligned

![image](https://user-images.githubusercontent.com/9795404/89226199-d1cf7200-d598-11ea-91c7-46c27c93d32d.png)

**Comment by MicaPete** [comment]
@bryantabaird - we will be moving to a different domain and layout soon, so I will not fix this in the meantime. I hope you understand.
