### ISSUE TITLE
How Can I find out the ID for the Virtual Report Suite?

### ISSUE THREAD

**Issue by kritikality** [AdobeDocs/analytics.en#128]
Issue in help/components/vrs/c-workflow-vrs/vrs-view.md

How Can I find out the ID for the Virtual Report Suite? It seems like it would make sense to document on this page

**Comment by kritikality** [comment]
Anyone able to look at this?? It's been 9 months and would be very useful to add to the documentation

**Comment by MicaPete** [comment]
@kritikality - profuse apologies for the very late reply.
Here is a link to the Analytics API that contains the best way to find the ID for a VRS:
https://www.adobe.io/apis/experiencecloud/analytics/docs.html#!AdobeDocs/analytics-2.0-apis/master/vrs.md

**Comment by MicaPete** [comment]
@kritikality - I had checked with engineering, and there is no way to get the VRS ID from the interface. Otherwise I would have most certainly indicated this option.  I will, however, add the API option to the documentation.

**Comment by MicaPete** [comment]
@kritikality - also, would you mind sharing your use case with us so that we can see how you are using this ID, thanks.

**Comment by MicaPete** [comment]
Bottom of the FAQ: https://experienceleague.adobe.com/docs/analytics/components/virtual-report-suites/vrs-faq.html?lang=en#virtual-report-suites

**Comment by kritikality** [comment]
HI @MicaPete - I know of at least one way of finding the report suite ID in Adobe Analytics.   I thought there would be a simpler way, but here it is.

1. Open a workspace Project
2. Click on the Report Suite Selector
3. Type anything in the search box
4. The IDs appear under the name
![image](https://user-images.githubusercontent.com/62052599/118206248-74f8d480-b4a5-11eb-99da-85fabfc42ccb.png)


Please do not use this screenshot as it belongs to a client!

Also, please note I am not familiar at all with the API (and neither are many other uesrs).  I cannot work out how to get the Virtual Report Suite ID from the documentation you have added. I can only see the definition.

**Comment by MicaPete** [comment]
That’s awesome, Kristi! Thanks for sharing.
I will add this to the doc on Monday.

--
Regards,
Meike

From: Kristi Barrow ***@***.***>
Date: Thursday, May 13, 2021 at 7:14 PM
To: AdobeDocs/analytics.en ***@***.***>
Cc: Meike Peters ***@***.***>, Mention ***@***.***>
Subject: Re: [AdobeDocs/analytics.en] How Can I find out the ID for the Virtual Report Suite? (#128)

HI @MicaPete<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicaPete&data=04%7C01%7Cmepeters%40adobe.com%7C2c7ae200ab824e7bac1808d9167596d1%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637565516564402146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BoVplTwqqYLJzGMNKlJ9dVGJnu8XTOi6%2BMeSE5MtzMQ%3D&reserved=0> - I know of at least one way of finding the report suite ID in Adobe Analytics. I thought there would be a simpler way, but here it is.

  1.  Open a workspace Project
  2.  Click on the Report Suite Selector
  3.  Type anything in the search box
  4.  The IDs appear under the name
[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F62052599%2F118206248-74f8d480-b4a5-11eb-99da-85fabfc42ccb.png&data=04%7C01%7Cmepeters%40adobe.com%7C2c7ae200ab824e7bac1808d9167596d1%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637565516564412138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wD31vvjwBzfcxV8hAl9rgTnb2tqEED%2FlbrEH9C3SenQ%3D&reserved=0>

Please do not use this screenshot as it belongs to a client!

Also, please note I am not familiar at all with the API (and neither are many other uesrs). I cannot work out how to get the Virtual Report Suite ID from the documentation you have added. I can only see the definition.

**Comment by kritikality** [comment]
Thanks @MicaPete - I see the documentation has been updated! :)
