### ISSUE TITLE
Update Launch section in writeSecureCookies 

### ISSUE THREAD

**Issue by tonypapousek** [AdobeDocs/analytics.en#132]
Launch supports [writeSecureCookies](https://github.com/AdobeDocs/analytics.en/blob/master/help/implement/vars/config-vars/writesecurecookies.md) as of Adobe Analytics Extension 1.8.2. Please update the doc accordingly.

Normally I'd just submit a PR, but I'm not too familiar with the [!UICONTROL Extensions] syntax being used or how to add the attached image in the Adobe-preferred way. Feel free to use this screenshot.

![Screen Shot 2020-08-25 at 5 38 38 PM](https://user-images.githubusercontent.com/962327/91235144-807b5400-e6fa-11ea-95ed-6b8dc4bb7b52.png)

Thanks!

**Comment by gigazelle** [comment]
Wonderful, thanks Tony! I've committed these changes, and they'll be live in the next day or so.

**Comment by tonypapousek** [comment]
Awesome, thanks!
