### ISSUE TITLE
Please update the link from YouTube to Adobe.com

### ISSUE THREAD

**Issue by mugdoor** [AdobeDocs/analytics.en#133]
Issue in help/analyze/analysis-workspace/curate-share/download-send.md

There is a link at the very bottom of the page to a video on YouTube. Please update the link to point to the internal video instead, which is at: https://docs.adobe.com/content/help/en/analytics-learn/tutorials/analysis-workspace/visualizations/intra-linking-in-analysis-workspace.html

Thanks!
Doug Moore

**Comment by MicaPete** [comment]
This should be updated now.
