### ISSUE TITLE
broken video on processing rules page

### ISSUE THREAD

**Issue by micahmorgan** [AdobeDocs/analytics.en#134]
Issue in ./help/admin/admin/c-processing-rules/processing-rules.md
there appears to be a video that should load on this page, but I am getting a blank placeholder
![image](https://user-images.githubusercontent.com/2581505/93273124-18fa7680-f785-11ea-9cfe-4b872c20d960.png)

**Comment by MicaPete** [comment]
Thank you. Fixed.
