### ISSUE TITLE
Virtual report suite link doesn't go to a real page

### ISSUE THREAD

**Issue by bkfarnsworth** [AdobeDocs/analytics.en#14]
Issue in help/implement/analytics-terminology-basics/ref-reports-report-suites.md

**Comment by bkfarnsworth** [comment]
Click this link and see it goes to a blank doc page:

![image](https://user-images.githubusercontent.com/6440842/61905243-dffaa500-aee5-11e9-8988-cc42f7d91ef8.png)

**Comment by MicaPete** [comment]
Hi @bkfarnsworth - this one is a bit tricky, since we have no equivalent Home page in the new doc system. Did you have this bookmarked or did you find it in the UI?

**Comment by MicaPete** [comment]
@bkfarnsworth - never mind - I think I know how to fix it.

**Comment by bkfarnsworth** [comment]
Hi @MicaPete I did not have it bookmarked, found this link while I was googling for documentation:

https://docs.adobe.com/content/help/en/analytics/implementation/analytics-basics/ref-reports-report-suites.html

I was just googling "what is a report suite"

That page had the link to the VRS page that does nothing.

**Comment by MicaPete** [comment]
Yes, I am fixing it now, @bkfarnsworth - I will fix a bunch of other links on that page as well. You will see it published this afternoon.

**Comment by MicaPete** [comment]
Fixed.
