### ISSUE TITLE
Wrong documentation on how to add access to Contribution Analysis

### ISSUE THREAD

**Issue by dankohn94041** [AdobeDocs/analytics.en#140]
Issue in ./help/analyze/analysis-workspace/virtual-analyst/contribution-analysis/ca-tokens.md

This page references old Analytics groups, which are no longer supported - it's all done via the Admin Console Product Profiles.  Need accurate steps for allowing a user to use Contribution Analysis that is not an Admin. The paragraph below is incorrect, this process no longer works:

How do I restrict access to Contribution Analysis? | By default, only admins have access to run Contribution Analyses, but admins can grant access to other users by creating a permission group in the Admin Console . You should give permission to use Contribution Analysis only to users who have a legitimate reason to use it and are trusted to not abuse their access.The permission is called "Contribution Analysis" under Analytics > Admin > User Management > Edit Groups > Edit All Report Access > Customize Report Suite Tools > Tools And Reports.
-- | --

**Comment by MicaPete** [comment]
Sorry about the delay!
https://experienceleague.adobe.com/docs/analytics/analyze/analysis-workspace/virtual-analyst/contribution-analysis/ca-tokens.html?lang=en#section_9278D58F21A840AA9B1ED1BD07A1EF0A
