### ISSUE TITLE
Encoding of Data Feed hit files is not always ISO-8859-1

### ISSUE THREAD

**Issue by rbloehm** [AdobeDocs/analytics.en#142]
Issue in https://github.com/AdobeDocs/analytics.en/blob/master/help/export/analytics-data-feed/c-df-contents/datafeeds-contents.md#hit-data-files

The documentation clearly says:

> All files are encoded using ISO-8859-1.

This is (at least for our Report Suite) not the case. The hit data files we receive are encoded in UTF-8, which can be easily checked due to the German Umlaute ä/ü etc. When decoding using UTF-8 they show up correctly and the way they are shown in the Adobe Analytics web frontend, and when using ISO-8859-1 they are Mojibaked. The report suite itself is set to UTF-8.

I don't know what the correct statement in the documentation is, needs to be checked with development probably.

Possible options are:

> All files are encoded using UTF-8.

> All files are encoded using the encoding selected for your report suite. You can check your report suite's encoding setting by [insert stuff here...]

**Comment by mcarriger** [comment]
Hello Robin,

The engineer for hit data files says the following:

"The encoding is ISO-8859-1.  I can understand that a customer can easily think it is something else, as bytes are read as ISO-8859-1 then written as ISO-8859-1.  If the bytes are not mutated (which is the case almost all of the time), they present as the same encoding that came into the system; so this encoding limitation is a non-issue for most customers.  There is, however, a chance that data can be mutated if character boundaries do not align well.  Thus we want to continue keep the ISO-8859-1 encoding documented."

Thanks so much for your feedback, though. It's good to re-check facts when people have questions.
