### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by matthew-lindley-bt** [AdobeDocs/analytics.en#149]
Issue in ./help/analyze/activity-map/activitymap-link-tracking/link-tracking-faq.md

%20%20 and the like are in this document.

Example:

<img&nbsp;onclick="s.tl(true,'o','abc')"&nbsp;src="someimageurl.png"/>%20%20%20%20%20%20%20%20%3C/code%3E%20%3C/p%3E%20%3C/li%3E%20%20%20%20%20%20%3Cli%20id=?lang=en"li_A93725B810FE408BA5E6B267CF8CEAE5"> Via the s_objectID variable

**Comment by MicaPete** [comment]
Hi, thanks for submitting this and sorry about the delay:

https://experienceleague.adobe.com/docs/analytics/analyze/activity-map/link-tracking/link-tracking-faq.html
