### ISSUE TITLE
More detail please

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/analytics.en#154]
Issue in ./help/components/segmentation/seg-reference/seg-operators.md

Please include some extra information on the contains clause and whether it is case sensitive or not.

Please include some examples of "Globbing" described in the Matches clause. If Matches supports regular expressions or wildcards, then please document what that looks like so we know how to use it correctly.

Ref: https://experienceleague.adobe.com/docs/analytics/components/segmentation/segment-reference/seg-operators.html?lang=en#segmentation

**Comment by MicaPete** [comment]
@Brontojoris - I am currently researching this issue.

**Comment by MicaPete** [comment]
Hi @Brontojoris - I have hopefully answered your questions here:
https://experienceleague.corp.adobe.com/docs/analytics/components/segmentation/segment-reference/seg-operators.html

**Comment by Brontojoris** [comment]
Thanks MicaPete, that's very helpful.
