### ISSUE TITLE
Broken/Redirected Link 

### ISSUE THREAD

**Issue by test-adobe** [AdobeDocs/analytics.en#157]
Issue in ./help/export/analytics-data-feed/c-df-contents/datafeeds-reference.md

The link - https://helpx.adobe.com/analytics/kb/merchandising-evar-instances-lookup-in-postproductlist.html gets redirected to the existing data feed documentation -  https://experienceleague.adobe.com/docs/analytics/export/analytics-data-feed/data-feed-contents/datafeeds-reference.html?#analytics-data-feed 

Could we kindly restore the prior link for merchandising eVar instances lookup in the post_product list?

**Comment by mcarriger** [comment]
I'm so sorry for the delay. I'm still trying to confirm if the original file is still valid or if any information has changed before I publish anything.

**Comment by mcarriger** [comment]
Hello, I've added the file back at https://experienceleague.adobe.com/docs/analytics/export/analytics-data-feed/data-feed-contents/merchandising-evar-lookup.html

I've set up a redirect from the old URL (https://helpx.adobe.com/analytics/kb/merchandising-evar-instances-lookup-in-postproductlist.html), and it should work sometime after 20:00 PST tonight.

Thanks so much for bringing it to our attention!
