### ISSUE TITLE
Trended Performance Chart very hard to understand by default

### ISSUE THREAD

**Issue by kritikality** [AdobeDocs/analytics.en#158]
Issue in ./help/analyze/analysis-workspace/c-panels/attribution.md

Can the "Trended Performance" table be explained more.  Selecting rows doesn't really seem to make sense as it shows the trended change in % per model.

Selecting a column shows the trended change in % over time for each channel which to me seems way more useful and intuitive (and matches the Chart Title "Trended performance of channels by attribution model".

**Comment by kritikality** [comment]
This is for the Attribution IQ panel

**Comment by mcarriger** [comment]
Updated the description of the Trended Performance visualization at https://experienceleague.adobe.com/docs/analytics/analyze/analysis-workspace/panels/attribution.html?lang=en#attribution-visualizations to explain that you can select rows AND columns to get different results.
