### ISSUE TITLE
The first link on the page does not work. 

### ISSUE THREAD

**Issue by dancingcactus** [AdobeDocs/analytics.en#16]
it takes me to the old doc site. 

Issue in help/implement/js-implementation/c-variables/sc-variables.md

**Comment by MicaPete** [comment]
@dancingcactus  - can you tell me on which page you clicked the link?

**Comment by MicaPete** [comment]
@dancingcactus - I think I misunderstood - will look at the page you indicated here...

**Comment by MicaPete** [comment]
@dancingcactus - I fixed the link - that page no longer exists. Instead, I linked to Page variables and Config variables.
