### ISSUE TITLE
Attribution models for Marketing Channels with "Override Last-Touch Channel" unchecked

### ISSUE THREAD

**Issue by kritikality** [AdobeDocs/analytics.en#160]
Issue in ./help/analyze/analysis-workspace/attribution/faq.md

Can the marketing Channels section be expanded to document what happens to Marketing Channels when the "Override Last-Touch Channel" is unchecked.  This information cannot be found anywhere and I am hearing conflicting views on this.

"Adobe provides generic ‘Marketing Channel’ and ‘Marketing Channel Detail’ dimensions so you can use them with your desired attribution model. These generic dimensions behave identically to Last Touch Channel dimensions" - this would indicate that a channel such as "Direct" would not override another channel on a Last Touch basis.  But what happens for other models such as linear and participation?

**Comment by kritikality** [comment]
Does anyone from Adobe look at these?  There has been no response here.

**Comment by mcarriger** [comment]
Hi Kristi,
The team is behind in resolving some issues. But someone has been assigned this one and should be working on it in the next week or so.
Thanks for pointing out this issue -- getting it fixed is important!

**Comment by MicaPete** [comment]
@kritikality - here is the response I got from Consulting:
"Custom attribution models like linear or participation will allocate credit only to non-null instances of a dimension. The MC configuration determines only when MC and MCD instances are written and how its persistence works, etc. If an MC configuration specifies that a channel match (like Direct) should not override last touch channel, then often the matches of that channel ruleset will not result in an MC instance. In those scenarios lacking an instance, there is nothing against which to attribute credit from a custom attribution model."

I hope that helps.
