### ISSUE TITLE
"End-of-life for Adobe Data Connectors" Enautics integration change request

### ISSUE THREAD

**Issue by jedediahmadsen** [AdobeDocs/analytics.en#161]
On the "End-of-life for Adobe Data Connectors" page (https://experienceleague.adobe.com/docs/analytics/import/dataconnectors/data-connectors-eol.html?lang=en#why-are-we-end-of-lifing-this-feature%3F) Enautics who builds the Official Oracle Data Connector has asked if we could change the listing from "deprecating" to "moving to the Exchange" since they are in the process of building an Exchange version of their integration.

**Comment by jedediahmadsen** [comment]
The Markdown page is: ./help/import/data-connectors/data-connectors-eol.md

**Comment by MicaPete** [comment]
@jedediahmadsen - I will make this change in the corporate git instance!

**Comment by MicaPete** [comment]
@jedediahmadsen - I assume you mean this one?
| Official Oracle Eloqua Integration | Migrating to Exchange |

**Comment by jedediahmadsen** [comment]
Yep! That’s the one. Thanks!

Jed Madsen  |  Partner Support Manager, Adobe Exchange DX  |  Adobe  |  c. 801.592.2796  |  ***@***.******@***.***>





On Apr 13, 2021, at 3:50 PM, MicaPete ***@***.******@***.***>> wrote:



@jedediahmadsen<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjedediahmadsen&data=04%7C01%7Cjmadsen%40adobe.com%7C57825108ee4f49b1bccc08d8fec630b0%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637539474458876082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LNC6gPMtlns4ebX8lC69fDbAu%2FDMR25WoImzTvZ8kRM%3D&reserved=0> - I assume you mean this one?
| Official Oracle Eloqua Integration | Migrating to Exchange |

**Comment by MicaPete** [comment]
@jedediahmadsen:
https://experienceleague.adobe.com/docs/analytics/import/dataconnectors/data-connectors-eol.html?lang=en#data-connector-partner-status
