### ISSUE TITLE
Use case for different replay configuration

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics.en#163]
Issue in ./help/components/cda/replay.md

Hi,
regarding the configuration of the "replay" to 1 or 7 days, can you please describe the pros/cons of the 2 possibilities?

Thanks

**Comment by mfreesto** [comment]
The advantage of the 7-day replay lookback window is that CDA is able to go back further in time to try to associate previously anonymous events with some person who later logged in within those 7 days. The disadvantages of the 7-day lookback window are 1) replay only runs once per week, and 2) the most recent 7 days are subject to change. 

The advantages of using the 1-day replay lookback window are 1) replay runs every day and 2) only yesterday is subject to change. The disadvantage of the 1-day lookback window is that CDA is only able to go back 1 day to try to associate previously anonymous events with a person who logged in yesterday.

**Comment by MicaPete** [comment]
https://experienceleague.adobe.com/docs/analytics/components/cda/faq.html

**Comment by angeli-adobe** [comment]
@mfreesto just to understand, in a scenario like this:
- DAY 1
- - anonymous 
- DAY 2
- - anonymous
- DAY 3
- - logged
With the 1-day replay only the data of day 2 are stitched to the logged customer, the data of day 1 still remain anonymous forever, am I right?
So, with 1-day replay I'm sure that on Day 3, I can do a report that leverage CDA, and be sure that the data up to day 1 are consolidated and will never change in the future, right?
One more question, I remember a replay with a lookback of 30 days, am I wrong? Is it changed recently?

Thanks

**Comment by mfreesto** [comment]
Answering via email.
