### ISSUE TITLE
Include 'lrt' parameter

### ISSUE THREAD

**Issue by amisharora** [AdobeDocs/analytics.en#164]
Issue in ./help/implement/validate/query-parameters.md

**Comment by mcarriger** [comment]
Hello, I added "lrt" to the page at https://experienceleague.adobe.com/docs/analytics/implementation/validate/query-parameters.html

Parameter:  lrt
Analytics implementation variable:  None
Description:  The “last request timing,” which is the roundtrip time for the last request, in milliseconds. It is sent only when more than one request is going out from a page or when the page is a single-page application (SPA).

I'm also continuing to check if there's anything else important to add.
