### ISSUE TITLE
PLease explain Tip Number 2

### ISSUE THREAD

**Issue by kritikality** [AdobeDocs/analytics.en#167]
Issue in ./help/components/c-marketing-channels/mchannel-best-practices.md

**There is no explanation as to why you would follow tip number 2.**  
What are the implications?
What if You have Direct as a channel with override configured?
IS there a video or more information available on this?

One of the best reasons for marketing channel was to rename "None" to Direct which makes more sense to the end users.  In your recommendation you are now expecting the end user to forget everything they have been told and go back to "none".  this is NOT what is used in the market and will only create confusion all over again.

This is a pretty fundamental change to how people are using Marketing Channels.  Please provide more information as to why you would go down this path.

**Comment by MicaPete** [comment]
Kristi,
I forwarded this question to the SME and should hear back soon...

**Comment by kritikality** [comment]
@MicaPete - how can I reopen this.
