### ISSUE TITLE
Marketing Channel Set up Wizard Still Includes Direct

### ISSUE THREAD

**Issue by kritikality** [AdobeDocs/analytics.en#171]
Issue in ./help/components/c-marketing-channels/mchannel-best-practices.md

The Marketing Cloud Set-up Wizard still includes Direct.  however this page recommends not setting this up.  This is likely to be confusing for people setting up Marketing Channels for the first time

![image](https://user-images.githubusercontent.com/62052599/118205789-81306200-b4a4-11eb-8a75-89d2265f6635.png)

**Comment by MicaPete** [comment]
@kritikality - I have let Engineering know that they should remove Direct and Internal, which is also discouraged, from the UI. Thanks.

**Comment by MicaPete** [comment]
@kritikality - this is now with Product Management and Engineering. It is up to them to get it removed from the UI.
