### ISSUE TITLE
missing "s.apl = " in code

### ISSUE THREAD

**Issue by webanalyticsninja** [AdobeDocs/analytics.en#172]
Issue in ./help/implement/vars/plugins/apl.md

I've noticed that in the section "Install the plug-in using AppMeasurement" the actual code example is missing "s.apl =". If you copy this code and use it as is, it will break the tracking as the s.apl is not defined.

**Comment by MicaPete** [comment]
@webanalyticsninja  - I am currently following up with Engineering on this issue.

**Comment by MicaPete** [comment]
@webanalyticsninja - this is the comment I received back from Engineering:

"I don't see a reason why s.apl is needed and just apl couldn't be used instead. On top of the page the apl function is declared globally so it can just be referenced directly.

That said, apl is a three-letter abbreviation that has a decent likelihood of colliding with other minimized JavaScript functions so perhaps it was previously assigned to the tracker object (s) to avoid that, and this documentation shows a little bit of both (which causes it to break).

 Looks like removing s. from all instances of s.apl on the documentation page should do the trick."

Does that help?
