### ISSUE TITLE
Missing details on process steps

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics.en#174]
Issue in ./help/components/vrs/c-workflow-vrs/vrs-create.md

Hi, this page should give on overview on how to create a VRS, but it actually explain only one of the 3 steps required. Can you please update with the remaining steps?

**Comment by MicaPete** [comment]
Thanks for alerting us to this missing information! Here is the updated page:

https://experienceleague.adobe.com/docs/analytics/components/virtual-report-suites/vrs-workflow/vrs-create.html?lang=en#define-settings
