### ISSUE TITLE
Broken link to Extensions Docs

### ISSUE THREAD

**Issue by syl-kim** [AdobeDocs/analytics.en#175]
Issue in ./help/implement/launch/create-analytics-property.md

Broken link: https://docs.adobelaunch.com/extension-reference/web/adobe-analytics-extension

**Comment by MicaPete** [comment]
Thanks for submitting this error. It has now been fixed:
https://experienceleague.adobe.com/docs/analytics/implementation/launch/create-analytics-property.html?lang=en#launch
