### ISSUE TITLE
Issues with delete examples.

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/analytics.en#176]
Issue in ./help/admin/c-data-governance/gdpr-labeling-example.md

There seem to be some issues with the sample Privacy delete requests. Two of the obvious issues are as follows:

1.  In the final three tables, in the final row, for Alice, the MyEvar3 values should be "Z" instead of "W".

2. In the final table for a DELETE request with expand IDs, the behavior seems fishy. The sample dataset uses two variables with the ID-DEVICE label, but when using expandIDs=true, it appears to only be expanding based on the AAID variable (which is the first ID-DEVICE), but not MyEvar3 (which is the second ID-DEVICE). If this is the true behavior of expandIDs, it should be made clear in the documentation that expandIDs are only determined from AAID, otherwise the table should be updated to also use MyEvar3 as an ID-DEVICE to determine how to anonymize the data. It looks like in the example, all the AAID values associated with the MyEvar3 ID-DEVICE in the set {X,Y,Z} should be anonymized as well as all the DEL-DEVICE labelled values in the last two rows where the ID-DEVICE MyEvar3=X and MyEvar3=Z.

**Comment by MicaPete** [comment]
@JMiller-Disco - this is the response from Engineering:
1. You are correct, the value should be a “Z” - this has been corrected in the doc.
2. The illustrated behavior is correct.
https://experienceleague.adobe.com/docs/analytics/admin/data-governance/gdpr-labeling-example.html?lang=en

**Comment by JMiller-Disco** [comment]
Actually, @MicaPete , I think there's still something off in the third example "user=Mary and expandIDs=true". Can you please walk through that example again because it doesn't make sense why only a single Device ID (MyEvar3) is anonymized without the DEL-PERSON label, but not the other one (AAID). Futher, the logic for expandID is only using the "77" and "88" values from from the Device-ID of AAID, but it is not expanding from the "X" and "Z" values of the other Device-ID (MyEvar3).
