### ISSUE TITLE
Update Best Practice Marketing Channel Classification to clearly specify Last/First touch needs to be classified

### ISSUE THREAD

**Issue by kritikality** [AdobeDocs/analytics.en#177]
Issue in ./help/components/c-marketing-channels/classifictions-mchannel.md

Can this page be updated to link to and from the Best practices page.  Also can the best practices page say that First/Last needs to be Classified, not "Marketing Channel"

https://experienceleague.adobe.com/docs/analytics/components/marketing-channels/mchannel-best-practices.html?lang=en

" In this case, we recommend that you create a classification for your Marketing Channels and leave those two channels unclassified." - is not obvious that you need to classify the "Last Touch" Channel

**Comment by MicaPete** [comment]
Hi @kritikality - I made these changes in the doc. Thanks for pointing them out.
https://experienceleague.adobe.com/docs/analytics/components/marketing-channels/mchannel-best-practices.html?lang=en
