### ISSUE TITLE
eVar Expiration should be Never

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/analytics.en#178]
Issue in ./help/implement/vars/plugins/websitebot.md

There is not eVar expiration setting named "Visitor". I think the documentation should read:

> Configure eVar settings: Set up an eVar under Conversion variables in Report suite settings. Set the expiration to “Never” and allocation to “Original Value (First)”.

Also, I am curios why Adobe Consulting are recommending updates to the AppMeasurement Library custom code. I think the correct implementation would be to create a Data Element, and then reference that data element in rule that sets Adobe Analytics variables.

REF: https://experienceleague.adobe.com/docs/analytics/implementation/vars/plugins/websitebot.html?lang=en#install-the-plug-in-using-appmeasurement

**Comment by MicaPete** [comment]
I am following up on this with Consulting, thanks Joris.

**Comment by MicaPete** [comment]
@Brontojoris - this page has been updated with new instructions and code samples. Thanks for logging this.
