### ISSUE TITLE
step 2 in Overall workflow of Transaction ID data sources

### ISSUE THREAD

**Issue by ankitsh2384** [AdobeDocs/analytics.en#179]
Issue in ./help/import/c-data-sources/c-datasrc-types/datasrc-transactionid.md
![datasource](https://user-images.githubusercontent.com/41048896/120589842-bfaba380-c3f6-11eb-9297-9e425731cb7b.JPG)

point 2 should be 

Follow the data source setup wizard to get an FTP location to upload data and download a data sources template file.

instead of 

Follow the data feed setup wizard to get an FTP location to upload data and download a data sources template file.

**Comment by MicaPete** [comment]
Thanks for noticing this error; it is now fixed:
https://experienceleague.adobe.com/docs/analytics/import/data-sources/data-types-and-categories/datasrc-transactionid.html?lang=en
