### ISSUE TITLE
column reference - missing column names

### ISSUE THREAD

**Issue by telstramedia** [AdobeDocs/analytics.en#18]
Issue in help/export/analytics-data-feed/c-df-contents/datafeeds-reference.md

some the column names are missing as follows :  

Column   Name
--
adclassificationcreative
adload
hier1
hier2
hier3
hier4
hier5
mobileacquisitionclicks
mobileactioninapptime
mobileactiontotaltime
mobileappperformanceaffectedusers
mobileappperformanceappid.app-perf-app-name
mobileappperformanceappid.app-perf-platform
mobileappperformancecrashes
mobileappperformancecrashid.app-perf-crash-name
mobileappperformanceloads
mobileappstoreavgrating
mobileappstoredownloads
mobileappstoreinapprevenue
mobileappstoreinapproyalties
mobileappstoreobjectid.app-store-user
mobileappstoreobjectid.application-name
mobileappstoreobjectid.application-version
mobileappstoreobjectid.appstore-name
mobileappstoreobjectid.category-name
mobileappstoreobjectid.country-name
mobileappstoreobjectid.device-manufacturer
mobileappstoreobjectid.device-name
mobileappstoreobjectid.in-app-name
mobileappstoreobjectid.platform-name-version
mobileappstoreobjectid.rank-category-type
mobileappstoreobjectid.region-name
mobileappstoreobjectid.review-comment
mobileappstoreobjectid.review-title
mobileappstoreoneoffrevenue
mobileappstoreoneoffroyalties
mobileappstorepurchases
mobileappstorerank
mobileappstorerankdivisor
mobileappstorerating
mobileappstoreratingdivisor
mobileavgprevsessionlength
mobilecrashes
mobilecrashrate
mobiledailyengagedusers
mobiledeeplinkid.name
mobileinstalls
mobilelaunches
mobileltvtotal
mobilemessageclicks
mobilemessageid.dest
mobilemessageid.name
mobilemessageid.type
mobilemessageimpressions
mobilemessagepushpayloadid.name
mobilemessageviews
mobilemonthlyengagedusers
mobileplacedwelltime
mobileplaceentry
mobileplaceexit
mobileprevsessionlength
mobilepushoptin
mobilepushpayloadid
mobilerelaunchcampaigntrackingcode.name
mobileupgrades
mvvar1
mvvar2
mvvar3
post_adclassificationcreative
post_adload
post_browser_height
post_browser_width
post_campaign
post_channel
post_clickmaplink
post_clickmaplinkbyregion
post_clickmappage
post_clickmapregion
post_cookies
post_currency
post_cust_hit_time_gmt
post_cust_visid
post_ef_id
post_event_list
post_hier1
post_hier2
post_hier3
post_hier4
post_hier5
post_java_enabled
post_keywords
post_mc_audiences
post_mobileaction
post_mobileappid
post_mobilecampaigncontent
post_mobilecampaignmedium
post_mobilecampaignname
post_mobilecampaignsource
post_mobilecampaignterm
post_mobiledayofweek
post_mobiledayssincefirstuse
post_mobiledayssincelastuse
post_mobiledevice
post_mobilehourofday
post_mobileinstalldate
post_mobilelaunchnumber
post_mobileltv
post_mobilemessagebuttonname
post_mobilemessageclicks
post_mobilemessageid
post_mobilemessageid.dest
post_mobilemessageid.name
post_mobilemessageid.type
post_mobilemessageimpressions
post_mobilemessageonline
post_mobilemessagepushoptin
post_mobilemessagepushpayloadid
post_mobilemessagepushpayloadid.name
post_mobilemessageviews
post_mobileosversion
post_mobilepushoptin
post_mobilepushpayloadid
post_mobileresolution
post_mvvar1
post_mvvar2
post_mvvar3
post_page_event
post_page_event_var1
post_page_event_var2
post_page_event_var3
post_page_type
post_page_url
post_pagename
post_pagename_no_url
post_partner_plugins
post_persistent_cookie
post_pointofinterest
post_pointofinterestdistance
post_product_list
post_prop1
post_prop2
post_prop3
post_prop4
post_prop5
post_prop6
post_prop7
post_prop8
post_prop9
post_prop10
post_prop11
post_prop12
post_prop13
post_prop14
post_prop15
post_prop16
post_prop17
post_prop18
post_prop19
post_prop20
post_prop21
post_prop22
post_prop23
post_prop24
post_prop25
post_prop26
post_prop27
post_prop28
post_prop29
post_prop30
post_prop31
post_prop32
post_prop33
post_prop34
post_prop35
post_prop36
post_prop37
post_prop38
post_prop39
post_prop40
post_prop41
post_prop42
post_prop43
post_prop44
post_prop45
post_prop46
post_prop47
post_prop48
post_prop49
post_prop50
post_prop51
post_prop52
post_prop53
post_prop54
post_prop55
post_prop56
post_prop57
post_prop58
post_prop59
post_prop60
post_prop61
post_prop62
post_prop63
post_prop64
post_prop65
post_prop66
post_prop67
post_prop68
post_prop69
post_prop70
post_prop71
post_prop72
post_prop73
post_prop74
post_prop75
post_purchaseid
post_referrer
post_s_kwcid
post_search_engine
post_socialaccountandappids
post_socialassettrackingcode
post_socialauthor
post_socialaveragesentiment
post_socialaveragesentiment (deprecated)
post_socialcontentprovider
post_socialfbstories
post_socialfbstorytellers
post_socialinteractioncount
post_socialinteractiontype
post_sociallanguage
post_sociallatlong
post_sociallikeadds
post_sociallink
post_sociallink (deprecated)
post_socialmentions
post_socialowneddefinitioninsighttype
post_socialowneddefinitioninsightvalue
post_socialowneddefinitionmetric
post_socialowneddefinitionpropertyvspost
post_socialownedpostids
post_socialownedpropertyid
post_socialownedpropertyname
post_socialownedpropertypropertyvsapp
post_socialpageviews
post_socialpostviews
post_socialproperty
post_socialproperty (deprecated)
post_socialpubcomments
post_socialpubposts
post_socialpubrecommends
post_socialpubsubscribers
post_socialterm
post_socialtermslist
post_socialtermslist (deprecated)
post_socialtotalsentiment
post_state
post_survey
post_t_time_info
post_tnt
post_tnt_action
post_transactionid
post_video
post_videoad
post_videoadinpod
post_videoadlength
post_videoadname
post_videoadplayername
post_videoadpod
post_videoadvertiser
post_videoauthorized
post_videocampaign
post_videochannel
post_videochapter
post_videocontenttype
post_videodaypart
post_videoepisode
post_videofeedtype
post_videogenre
post_videolength
post_videomvpd
post_videoname
post_videonetwork
post_videopath
post_videoplayername
post_videoseason
post_videosegment
post_videoshow
post_videoshowtype
post_visid_high
post_visid_low
post_visid_type
post_zip
prop1
prop2
prop3
prop4
prop5
prop6
prop7
prop8
prop9
prop10
prop11
prop12
prop13
prop14
prop15
prop16
prop17
prop18
prop19
prop20
prop21
prop22
prop23
prop24
prop25
prop26
prop27
prop28
prop29
prop30
prop31
prop32
prop33
prop34
prop35
prop36
prop37
prop38
prop39
prop40
prop41
prop42
prop43
prop44
prop45
prop46
prop47
prop48
prop49
prop50
prop51
prop52
prop53
prop54
prop55
prop56
prop57
prop58
prop59
prop60
prop61
prop62
prop63
prop64
prop65
prop66
prop67
prop68
prop69
prop70
prop71
prop72
prop73
prop74
prop75
resocialpageviews
socialaveragesentiment
socialaveragesentiment (deprecated)
socialfbstories
socialfbstorytellers
socialinteractioncount
sociallikeadds
sociallink
sociallink (deprecated)
socialmentions
socialpageviews
socialpostviews
socialproperty
socialproperty (deprecated)
socialpubcomments
socialpubposts
socialpubrecommends
socialpubsubscribers
socialterm
socialtermslist
socialtermslist (deprecated)
socialtotalsentiment
sourceid
ssocialpubsubscribers
videoauthorized
videoaverageminuteaudience
videochaptercomplete
videochapterstart
videochaptertime
videopause
videopausecount
videopausetime
videoplay
videoprogress10
videoprogress25
videoprogress50
videoprogress75
videoprogress96
videoqoebitrateaverage
videoqoebitratechange
videoqoebuffer
videoqoedropbeforestart
videoqoedroppedframes
videoqoeerror
videoresume
videototaltime
videouniquetimeplayed
batch_date

**Comment by gigazelle** [comment]
Hi there, thanks so much for your feedback! Almost all of these column omissions are by design:

- Some columns, like mvvar2, hier4, and prop50 are custom variables, and the same concept applies to similar custom variables. These columns are aggregated into hier1-hier5, prop1-prop75, etc.
- Post columns are omitted because they contain the same content as their non-post counterparts. The notice at the top of the page outlines this. Readability is important, and doubling the size of the table for post columns would not provide any value.
- The rest of the columns, including many mobile, social and video columns, are actually not supposed to be in the data feed UI. If you notice any data in any of these mobile, social, or video columns, please let me know - but from what I understand, these columns actually belong as a number within event_list.

Outside the aggregated and post columns, do any of these columns have any data in any report suite for you?
