### ISSUE TITLE
404 error in CJA - Create Connection guide

### ISSUE THREAD

**Issue by pertusine** [AdobeDocs/analytics.en#180]
Step 1: Go to: https://experienceleague.adobe.com/docs/analytics-platform/using/cja-connections/create-connection.html?lang=en

Step 2: Click on “here” as shown below and you are taken to 404 page

![CJA_DataSources_404](https://user-images.githubusercontent.com/9814627/120860652-e07d1180-c53a-11eb-9441-49f1e37698bd.png)

https://experienceleague.adobe.com/docs/platform-learn/tutorials/cja/connecting-customer-journey-analytics-to-data-sources-in-platform.html?lang=en

RNT #210527-000253

**Comment by MicaPete** [comment]
Thanks @pertusine - this link has been fixed.
