### ISSUE TITLE
Screenshots only showing part of segment definitions

### ISSUE THREAD

**Issue by brentrad-acn** [AdobeDocs/analytics.en#183]
Issue in ./help/technotes/cookies/cookies.md

The ITP Visits segment found on this page refers to (Big Sur + Safari) or iOS 14.2+, but the screenshots in the "How can I determine if Safari changes affect my business?" only refer to iOS 14.2+. Rather than show a screenshot of what is available from the tooltip, it may be better to include a screenshot of the segment builder so that users can see the entire set up.

Additionally, the page content should probably be updated as macOS Monterey is currently in beta and is expected to be released later in 2021.

**Comment by MicaPete** [comment]
@mcarriger - can you look at this?

**Comment by MicaPete** [comment]
@brentrad-acn - I hope this is what you are looking for:
https://experienceleague.adobe.com/docs/analytics/technotes/cookies/cookies.html?lang=en
