### ISSUE TITLE
The length limit is set by product name / category name

### ISSUE THREAD

**Issue by immany** [AdobeDocs/analytics.en#185]
Issue in ./help/implement/vars/page-vars/products.md

In this help, there is a 100-byte limit per product, however this length limit is for "Category" and "Product" fields of product variables. This description makes the new customer a little confused. 

--------
While there is a 100-byte limit per product, the total length for the products variable is 64K. 
-------

**Comment by MicaPete** [comment]
@gigazelle - please look at this when you return.

**Comment by gigazelle** [comment]
Hi @immany - happy to help here, but I need to know a little more around how a new customer is confused. Each individual product has a limit of 100 bytes, however the products variable can include many products. The limit for the entire product string is 64k, while the limit for a single product within the product string is 100 bytes.

Here is the verbiage that currently exists on the page:

> This variable supports multiple products in the same hit. It is valuable for shopping cart and purchases containing multiple products. While there is a 100-byte limit per product, the total length for the `products` variable is 64K. Separate each product with a comma (`,`) in the string.

If you have any recommendations to adjust the wording and make it clearer, I'd be happy to incorporate it. Thanks!

**Comment by immany** [comment]
@gigazelle thanks for your reply. The product variable has many fields like category, name, price, etc. This 100-byte limit is for every category and name, not for product. So my recommendation is changing 100-byte limit per category and name filed. In fact, one of our customer is asking for clarifying if the limit is for per filed or per product. Thanks.

**Comment by gigazelle** [comment]
@immany Okay I got this figured out after doing some digging on my end. It is indeed a 100 byte limit per category field, and a 100 byte limit per product name field. I have committed those clarifications to the page. Please let me know you or the customer need any additional clarification after these changes. Thanks!
