### ISSUE TITLE
s.eVar1=s.getNewRepeat();

### ISSUE THREAD

**Issue by amisharora** [AdobeDocs/analytics.en#186]
Issue in ./help/implement/vars/plugins/getnewrepeat.md

The s.getNewRepeat() throws an error. Only getNewRepeat() needs to be called without "s." for proper functioning of the plugin.

**Comment by MicaPete** [comment]
@gigazelle - please look at this when you return.

**Comment by gigazelle** [comment]
Thank you @amisharora! Good catch - I have updated the doc. Updates should be published by tomorrow. We appreciate you taking the time to report this!
