### ISSUE TITLE
Virtual Report Suites, Data Sources, and Segments

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics.en#187]
Issue in ./help/components/vrs/vrs-considerations.md

The section has errors:

> **Summary data sources**
> Summary data sources let you import aggregated metrics into Adobe Analytics at a report-suite level. Because summary data source uploads contain aggregated metrics, they cannot be segmented. Since VRS operates using segmentation, all data imported using summary data sources are not available in virtual report suites. Summary data sources are only visible in the source report suite.

The above paragraph is true for Visit and Visitor segments, but Hit containers are able to segment data source rows under the right rule conditions. This section should be updated to state something along the lines of:

> **Summary data sources**
> Summary data sources let you import aggregated metrics into Adobe Analytics at a report-suite level. Because summary data source uploads contain aggregated metrics _without a visitor ID_, they cannot be segmented in Visit and Visitor containers. Since VRS operates using segmentation, data imported using summary data sources _will not be_ not available in virtual report suites _if the segment is built using a Visit or Visitor container_. 
> 
> Summary data sources _will show up in the virtual report suite if a Hit container is used and if that Hit container has rules conditioned to include the data source information._

**Comment by MicaPete** [comment]
@jtwood426 - thanks for pointing this out -I have made this changes in the documentation.
