### ISSUE TITLE
Incorrect Logic Group

### ISSUE THREAD

**Issue by aablank1** [AdobeDocs/analytics.en#19]
Issue in help/components/c-segmentation/c-segmentation-workflow/seg-sequential-build.md
The Logic Group first match display example is incorrect.  Shouldn't the Logic Group should be in the first group rather than the single second page?

**Comment by MicaPete** [comment]
Thanks for submitting this issue, @aablank1 - it helps us improve the documentation. I have fixed this issue and will close it once the content is published.

**Comment by MicaPete** [comment]
@aablank1  - I am adding additional clarification around Log Groups, just FYI.

**Comment by justlee-adobe** [comment]
Hello,

Please confirm if this code is correct. I believe there might be an error due to copy/paste.

```
<a href="./popup.html" target="_blank" onClick="<a href="./popup.html" onclick="s.tl(this,'o','popup',null,'navigate');javascript:window.open('./popup.html','popup','width=550,height=450'); 
return false;">

```

**Comment by MicaPete** [comment]
https://docs.adobe.com/content/help/en/analytics/components/segmentation/segmentation-workflow/seg-sequential-build.html#logic-group-containers
