### ISSUE TITLE
Column Missing in Clickstream Data Column Reference

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics.en#190]
Issue in ./help/export/analytics-data-feed/c-df-contents/datafeeds-reference.md

Hello,

In the data feed UI, there is an option to add a column called 'sampled_hit'. That column is missing in the documentation. Are you able to update the documentation to close this gap?

**Comment by jtwood426** [comment]
![7-20-2021 11-33-25 PM](https://user-images.githubusercontent.com/53830010/126426590-93ae3832-40bd-4707-a5a7-692cb3b38e75.png)

**Comment by gigazelle** [comment]
Hi @jtwood426, thank you for finding this gap! I have started conversations internally to obtain that info - once I have it, I'll publish it and update you here.

**Comment by gigazelle** [comment]
Hi @jtwood426, this is actually an oversight by our engineering team. It is an Adobe-internal column that is no longer used, and was not intended to be visible in the Data Feeds manager. Engineering will be removing that column in an upcoming update, so there is no documentation to update at this time.
If your curiosity is as great as mine, here's what the column used to do: Previous versions of Analytics (particularly Ad Hoc Analysis) sampled large data sets, and this column was used as a flag to determine if the hit was part of sampling. Current versions of Analytics no longer use sampling, so this column does not represent anything meaningful at this point in time.
Thank you for reporting the issue, and please feel free to reply with any other questions!
