### ISSUE TITLE
Please link to Automatically Mapped Variables page

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/analytics.en#195]
Can you please link this page to the following page? I think it would be tremendously helpful:
https://experienceleague.adobe.com/docs/experience-platform/edge/data-collection/adobe-analytics/automatically-mapped-vars.html

Issue in ./help/implement/aep-edge/xdmoverview.md

**Comment by gigazelle** [comment]
Great idea! This has been added with commit 2a4b473.
