### ISSUE TITLE
Changes needed to the product string documentation page

### ISSUE THREAD

**Issue by mugdoor** [AdobeDocs/analytics.en#198]
Issue in ./help/implement/vars/page-vars/products.md

Hi y'all,
We had a customer concerned that this page doesn't have the same warning about the deprecated category field that is listed in the Merchandising Evar page here: https://experienceleague.adobe.com/docs/analytics/admin/admin-tools/conversion-variables/merchandising-evars.html?lang=en

On that page, look for "Category is a deprecated feature..."

I also notice that although we have a lot of examples on the product string page, we don't actually have the format of the string anywhere on the page. Seems like we should put it in there, maybe right above the explanation of the individual fields.

Also, many of the examples on the product string page have the category in them, even though it is deprecated.
Can we please:
1. put the product string format on the page
2. include a warning that the category field is deprecated, but that we have to leave the space for it so that we don't change the format of the string for all of the implementations out there. So all product strings should start with the semi-colon, signifying the empty first field
3. remove the category from the examples

Thanks! Let me know if you have any questions.

Doug Moore

**Comment by MicaPete** [comment]
@mugdoor - please refer to https://jira.corp.adobe.com/browse/AN-275468 
for an answer by Ken McKell. I have adjusted the product var doc accordingly.
https://experienceleague.adobe.com/docs/analytics/implementation/vars/page-vars/products.html?lang=en
