### ISSUE TITLE
Dead Links: GDPR UI and GDPR API

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics.en#20]
On https://docs.adobe.com/content/help/en/analytics/admin/data-governance/gdpr-submit-access-delete.html

The Submit Requests section links pointing to...

https://www.adobe.io/apis/cloudplatform/gdpr/docs/alldocs.html#!api-specification/markdown/narrative/gdpr/using-gdpr-ui.md and
https://www.adobe.io/apis/cloudplatform/gdpr/docs/alldocs.html#!api-specification/markdown/narrative/gdpr/use-cases/gdpr-api-overview.md

...end up loading a Page Not Found error.

**Comment by MicaPete** [comment]
Thanks for submitting this issue, @jtwood426. I have fixed these links and will close the issue once everything is published.
