### ISSUE TITLE
HTTP Header keys

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics.en#205]
Issue in ./help/admin/admin/c-server-side-forwarding/ssf-reference.md

From a customer perspective, the keys for the HTTP Headers signals are not so clear. For example "Referer" in AAM is mapped to "h_referer". Worth to add a column that specify the keys available in AAM.

**Comment by MicaPete** [comment]
Engineering is working on this now...

**Comment by angeli-adobe** [comment]
Thanks @MicaPete for the update.

**Comment by MicaPete** [comment]
Hi @angeli-adobe - here is the information you requested:
https://experienceleague.adobe.com/docs/analytics/admin/admin-tools/server-side-forwarding/ssf-reference.html?lang=en#section_0549705E76004F9585224AEF872066C0

**Comment by angeli-adobe** [comment]
Hi @MicaPete thanks for the update! Now it's more clear!
