### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by badde-media** [AdobeDocs/analytics.en#206]
https://helpx.adobe.com/analytics/kb/troubleshoot-billing.html
links to
Issue in ./help/admin/c-server-call-usage/overage-overview.md

**Comment by MicaPete** [comment]
@gigazelle

**Comment by gigazelle** [comment]
Hi Daniel, can you please elaborate what the issue is? We retired the helpx domain several years ago, and moved all the content to Experience League.

**Comment by badde-media** [comment]
Hi, the problem was that I had a billing issue for my CC subscription and the help text that I've found that should link to that content was gone. I could resolve the billing issue, but you might want to check your help system for missing links on this topic.
