### ISSUE TITLE
Download link doesn't take you to anywhere useful

### ISSUE THREAD

**Issue by swervo** [AdobeDocs/analytics.en#21]
Issue in help/implement/js-implementation/javascript-implementation-overview.md

This page doesn't provide a link where code download is available. Where it says:

'The download is available in code manager' with code manager being a link - following the link doesn't take you to anywhere useful.

I still don't know where I can download the AppMeasurement.js and VisitorAPI.js code from and I've been searching for about 30 minutes. What am I not understanding here?

**Comment by MicaPete** [comment]
@swervo - I assume you have a login to Analytics? Log in and go to Admin > Code Manager. That is where the download files are. I will modify the doc to make this clearer.

**Comment by swervo** [comment]
@MicaPete Thanks.

I did have a log in but seemingly insufficient permissions to actually download the code - code manager was empty for me once I figured out that was where to look for downloads.

**Comment by MicaPete** [comment]
You won't be able to download unless you have Admin permissions, @swervo...
