### ISSUE TITLE
Update Privacy Services FAQ to Describe Anonymization Method

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics.en#210]
Issue in ./help/admin/c-data-governance/gdpr-faq.md

Can we please add a response to the question: "How is data anonymized?"

Previously, Product Management (Marijka Engel) has provided this response:

“[The] existing value is replaced with: "GDPR-[32-digit hexadecimal]".  The value is a cryptographically strong 128-bit pseudorandom number. There is no way to determine the original value from this new value, and no way to derive the new value knowing the original value. For a given variable in a single Privacy request, if an identical value as that being replaced occurs within other hits that are also being deleted, all instances of that value will be replaced with the same value.”

If it is possible to get an updated response from Product for client-facing documentation in the FAQ, it would help during client engagements.

**Comment by MicaPete** [comment]
@jtwood426 - we are looking at this issue now.

**Comment by jtwood426** [comment]
@MicaPete I found out this question is documented on a separate page (https://experienceleague.adobe.com/docs/analytics/admin/data-governance/gdpr-labels.html?lang=en)

**Comment by MicaPete** [comment]
@jtwood426  - good to know. I will close this issue then.
