### ISSUE TITLE
Add the link for "How to see data retention policy"

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/analytics.en#213]
Issue in ./help/technotes/data-retention.md

It would be nice if FAQ on this page https://experienceleague.adobe.com/docs/analytics/technotes/data-retention.html?lang=en contains a link to https://experienceleague.adobe.com/docs/analytics/admin/data-governance/gdpr-view-settings.html?lang=en with a topic "How to see/validate current data retention policy".

**Comment by NaincyKumariKnoldus** [comment]
Hey @himanshu-pathak Can I do this?

**Comment by MicaPete** [comment]
@himanshu-pathak - here you go:

https://experienceleague.adobe.com/docs/analytics/technotes/data-retention.html?lang=en
