### ISSUE TITLE
Broken Link for Privacy API

### ISSUE THREAD

**Issue by anhousto** [AdobeDocs/analytics.en#216]
Issue in ./help/admin/c-data-governance/gdpr-faq.md

on this page, https://experienceleague.adobe.com/docs/analytics/admin/data-governance/gdpr-labels.html?lang=en The link for the privacy API in the first row takes you to a page not found

**Comment by MicaPete** [comment]
@anhousto - this link has been fixed - thanks.
https://experienceleague.adobe.com/docs/analytics/admin/data-governance/gdpr-faq.html?lang=en
