### ISSUE TITLE
Please fix the link of the document for Adobe Analytics API on Adobe I/O

### ISSUE THREAD

**Issue by immany** [AdobeDocs/analytics.en#217]
Issue in ./help/analyze/reporting-api.md

The link of the document for Adobe Analytics API on Adobe I/O has been updated to https://developer.adobe.com/analytics-apis/docs/2.0/ insead of https://adobe.io/analytics-apis/docs. Please update the link. Thanks.

**Comment by MicaPete** [comment]
@immany - this issue has now been fixed. Thank you.

**Comment by immany** [comment]
@MicaPete Thank you very much for fixing this promptly.
