### ISSUE TITLE
Events in all supported languages

### ISSUE THREAD

**Issue by loldenburg** [AdobeDocs/analytics.en#218]
Issue in ./help/admin/admin/logs.md

The page shows only the Event Names in English. However if people use Adobe Analytics in another language, the logs are in that particular language. Please add a list of all events in all language versions so we don't need to waste days to figure out all variants...

**Comment by MicaPete** [comment]
@loldenburg - you can access the language versions by clicking the globe icon at the top right of the Help page, then selecting the language in which you wish to view the events.
![globe](https://user-images.githubusercontent.com/19596669/154525549-b6d675d4-c2d8-4c60-a5d8-a2dddb660b51.png)

**Comment by loldenburg** [comment]
@MicaPete that is not what I meant. That is an autotranslation which means it is terrible to read, and what we really need is to make sense of the multitude of languages in the Logs. So even for English, the Event Names do not reflect what we get in the logs. There needs to be a list of the exact wording. Otherwise we spend weeks just trying to figure out stuff like this: 
The same Events logged in many different languages... An absolute horror to do any analysis on. So if you want people to use the logs for something useful, you need to provide proper documentation.
![image](https://user-images.githubusercontent.com/16238928/154532902-f5c24290-7333-4811-9048-79aa9788ac72.png)

**Comment by MicaPete** [comment]
@gigazelle - can you take a look at this?

**Comment by gigazelle** [comment]
Hi Lukas, this is an excellent point that you bring up. Meike and I will talk with PM/engineering to get their take on making logs language-agnostic. The outcome I hope to achieve is a product update where events are recorded the same regardless of language. If the powers that be determine that this is WAD, then we will get each event documented in each language.

**Comment by gigazelle** [comment]
Hi Lukas, we finished the meeting today. We are tracking this internally via AN-284631. Feel free to reach out to me on Slack if you'd like to check in on it. Thanks!
