### ISSUE TITLE
Add a point that mentions to change the ‘AND’ statement, to an ‘OR’ statement (as it will default to ‘AND’). 

### ISSUE THREAD

**Issue by aorozco-adobe** [AdobeDocs/analytics.en#221]
Issue in ./help/technotes/event/segments.md

https://experienceleague.adobe.com/docs/analytics/technotes/event/segments.html?lang=en#:~:text=%20Exclude%20specific%20dates%20in%20analysis%20%201,exactly%20as%20you%20would%20use%20other...%20More%20

I can’t see anywhere that mentions the part where you will need to change the ‘AND’ statement, to an ‘OR’ statement (as it will default to ‘AND’). So unless you pick up on this in the screenshot, you could miss this crucial step.

Might be something to update on the steps to ensure it’s not missed?

**Comment by MicaPete** [comment]
@aorozco-adobe - I added a Tip to this effect in the document. Thanks for bringing this up!
https://experienceleague.adobe.com/docs/analytics/technotes/event/segments.html?lang=en#:~:text=%20Exclude%20specific%20dates%20in%20analysis%20%201,exactly%20as%20you%20would%20use%20other...%20More%20
