### ISSUE TITLE
prodView Metric Does Not Increment When post_event_list Contains ANY Event

### ISSUE THREAD

**Issue by Adobe-BSavage** [AdobeDocs/analytics.en#222]
Issue in ./help/components/metrics/product-views.md

It seems this documentation on the second bullet point is incorrect with current practice:
This metric counts the number of hits that match either of the following:

The value prodView exists in the [events](https://experienceleague.adobe.com/docs/analytics/implementation/vars/page-vars/events/events-overview.html?lang=en) variable; or
The [products](https://experienceleague.adobe.com/docs/analytics/implementation/vars/page-vars/products.html?lang=en) variable is set, and no shopping cart events exist in the events variable. Any event that is not custom (event1 - event1000) is a shopping cart event.

Data is showing that if ANY event is set in post_event_list that a prodView won't be incremented. 
This specifically states shopping cart events outside of Custom Success Events (1-1000) can't exist. If they don't, prodView will be incremented. We have raw data from a debug.log which shows prodView not being incremented when only Custom Success Events exist. This data conflicts with the document.

Please confirm and update the document to the current practice that a products variable must be set and there can be NO event set in post_event_list in order for a prodView to increment.

**Comment by gigazelle** [comment]
Thank you for your feedback - #220 referenced this exact issue. It has been resolved with the latest commit.
