### ISSUE TITLE
File automatically deleted from FTP repo

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/analytics.en#223]
Issue in ./help/components/classifications/importer/c-uploading-saint-data-files-via-ftp.md

Hi, based on my experience, once Adobe Analytics read and process a file uploaded in the FTP folder, then the files are deleted by Analytics itself. Can you please confirm and update the documentation accordingly?

**Comment by MicaPete** [comment]
Yes, @angeli-adobe, the files are indeed automatically deleted. I will add this to the doc.
