### ISSUE TITLE
JavaScript Issue with websiteBot Custom Code

### ISSUE THREAD

**Issue by rcalentine** [AdobeDocs/analytics.en#224]
Issue in ./help/implement/vars/plugins/websitebot.md
I tried installing the websiteBot plugin Mouse Move Listen custom code and when I copy and paste the code, I am getting an error message. When I try to resolve the error based on JS debugging editors, then I get other errors further down in the code. I event tested this with JSLint and I received the same error message. Any thoughts on how to resolve this issue? Without resolving the issue I cannot save the rule.

Screen shot of rule custom editor in Adobe Tags
![2022-04-04_16-49-10](https://user-images.githubusercontent.com/103002452/161638014-78534fba-1486-4214-8948-da1b131c2102.png)

Screen shot of JSLint
![2022-04-04_16-51-37](https://user-images.githubusercontent.com/103002452/161638463-b2f459e7-b467-45e5-8e0b-c4e6fd03a8f4.png)

**Comment by 21msweeney** [comment]
You have to remove all the line breaks. For example, remove the line breaks for lines 4-7, it should all be on one line. Do the same for lines 9-26.

**Comment by MicaPete** [comment]
@rcalentine - does this answer your question? Thanks, @21msweeney!

**Comment by MicaPete** [comment]
@rcalentine - here is another comment from an engineer:  I believe the client could resolve the issue if they remove the line breaks and wrap the regex in parentheses.  Since this code was intended to use within Launch, it should work there without being linted.
