### ISSUE TITLE
Additional Clarification for Scope

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics.en#226]
Issue in ./help/technotes/ip-addresses.md

Hello,

There is confusion about whether or not this documentation applies to outbound Analytics systems, like Data Warehouse and Data Feeds. If these IP blocks do apply to outbound features, could that information please be called out more specifically? And if services like Data Warehouse and Data Feeds are not covered by this document, could we please have that added to Experience League?

**Comment by MicaPete** [comment]
@gigazelle - can you address this one, please?

**Comment by gigazelle** [comment]
Hi @jtwood426, yes, the IP addresses include both inbound (data collection and ingestion) and outbound (downloaded reports and emails) systems that Analytics relies on. I'll add a note that specifically calls that out. Thanks!
