### ISSUE TITLE
TikTok missing from list of Social Networks

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#227]
Issue in ./help/components/dimensions/referrer-type.md

tiktok.com should be added to the list.

There may be other regional TikTok domains that need to be included.

**Comment by MicaPete** [comment]
@inselaffe - I added tiktok.com, and am checking with Engineering on other tiktok domains that are part of the  ‘Social networks’ lookup table that Adobe uses. Will add those once I hear back. Thanks!
