### ISSUE TITLE
Training video cut or not fully loaded.

### ISSUE THREAD

**Issue by Julian-Naranjo-AC** [AdobeDocs/analytics.en#228]
Issue in ./help/analyze/analysis-workspace/virtual-analyst/contribution-analysis/ca-tokens.md

Training video cut or not fully loaded.

https://experienceleague.adobe.com/docs/analytics/analyze/analysis-workspace/virtual-analyst/contribution-analysis/ca-tokens.html?lang=en

**Comment by MicaPete** [comment]
@Julian-Naranjo-AC - I am sorry, but I cannpt reproduce this error you are getting. The video works fine for me.

**Comment by MicaPete** [comment]
Or try watching it on YouTube:
https://www.youtube.com/watch?v=MbpeJIADtGk
