### ISSUE TITLE
CEDDL still recommended as best practice in docu although ACDL now recommended from PM and Consulting

### ISSUE THREAD

**Issue by prokopiu** [AdobeDocs/analytics.en#234]
It says: 

_The recommended overarching data layer object to use is digitalData. The following example lists a somewhat comprehensive data layer JSON object with example values:_

_Adobe recommends following the [Customer Experience Digital Data Layer](https://www.w3.org/2013/12/ceddl-201312.pdf) outlined by the [Customer Experience Digital Data Community Group](https://www.w3.org/community/custexpdata/). Use the following sections to understand how data layer elements interact with Adobe Analytics._

Our customer SAP gets conflicting messages from Adobe Consulting and Product Management, who are calling ACDL the best practice to use and not the older CEDDL approach documented here.

Will this be updated any time soon?

Kosta Prokopiu, TAM

**Comment by MicaPete** [comment]
@prokopiu - you are correct. I checked with Analytics and they say that ACDL is preferred. We will be updating this doc within a week. Thanks.

**Comment by MicaPete** [comment]
@prokopiu - I will assign a Jira ticket to @gigazelle to update the doc.
