### ISSUE TITLE
productListItems[].lineItemId	does not exist in any schema

### ISSUE THREAD

**Issue by stewartschillingsdi** [AdobeDocs/analytics.en#235]
Issue in ./help/implement/aep-edge/variable-mapping.md

This document states that _productListItems[].lineItemId_  automatically translates to the _Category dimension_ of the AA product string.

This seems like an odd mapping in the first place, but beyond that, "lineItemId" is not a field provided within productListItems[].
Since there is no schema field productListItems[*].lineItemId, there is no way to create an edge mapping to populate it.

**Comment by MicaPete** [comment]
@stewartschillingsdi - I received this reply from Adobe internally: This is a known issue. The XDM is missing a proper field for this. We plan to update the XDM.
Thanks for bringing this up - we will update the documentation accordingly.
