### ISSUE TITLE
Is there a mapping to populate s.transactionID?

### ISSUE THREAD

**Issue by stewartschillingsdi** [AdobeDocs/analytics.en#237]
Issue in ./help/implement/aep-edge/variable-mapping.md

I don't see an automatic mapping for s.transactionID.  Does one exist?

**Comment by gigazelle** [comment]
No, there is no automatic mapping for `transactionID`, at least not one officially supported by Adobe.

**Comment by stewartschillingsdi** [comment]
This seems like a miss.  s.transactionID is a pretty important variable for quite a few AA customers.  Any e-commerce customer who wants to upload order data after the fact (returns, cost of goods, etc) needs to set this.  I understand that I can set it using a processing rule, but why should this be the exception when (seemingly) every other variable has an automatic mapping?  I also understand that this is the repo for the docs, but can you advise me on who to contact regarding the functionality?

**Comment by gigazelle** [comment]
sooooo I completely misunderstood your question - I thought that you were referring to some kind of tool that automatically generates a transaction ID. That's 100% my bad - my apologies!

`transactionID` is mapped to `commerce.order.transactionID`. It was added to the docs with e42c125 - it was in the works when the variable mapping docs were authored, so it was added a bit later.

**Comment by stewartschillingsdi** [comment]
Perfect!  Thank you, Russ.

-Stew

**Comment by stewartschillingsdi** [comment]
It seems that guidance has changed (just in case anyone stumbles into this issue looking for the answer).  
The path is now : `commerce.order.payments[0].transactionID`
See here: https://github.com/AdobeDocs/analytics.en/commit/b6a92b8ca79422d2ba857cd98c172a824658a7a6
