### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by jay-nike** [AdobeDocs/analytics.en#238]
Issue in ./help/analyze/analysis-workspace/components/apply-create-metrics.md
Please correct Components typo - refer screenshot
![image](https://user-images.githubusercontent.com/110047283/188137883-c2d0a28e-edc3-460e-b648-40481db3106e.png)

**Comment by MicaPete** [comment]
@jay-nike - Thanks for noticing this. The typo has been fixed.
