### ISSUE TITLE
Hierarchies are missing from this documentation

### ISSUE THREAD

**Issue by stewartschillingsdi** [AdobeDocs/analytics.en#239]
Issue in ./help/implement/aep-edge/variable-mapping.md

The hierarchies (hier1 - hier5) are missing from this documentation. 

<img width="368" alt="Screen Shot 2022-09-02 at 12 25 47 PM" src="https://user-images.githubusercontent.com/22940746/188206540-5469d276-724c-4cac-82c1-7fea49323ad7.png">

I have tested setting hierarchy info using the xdm schema path, _experience.analytics.customDimensions.hierarchies.hier1 and have found that the automatic mapping to the "h1" analytics variable is working fine.

**Comment by gigazelle** [comment]
Thank you for pointing this out! I've updated the documentation to reflect this.

It's worth noting that hierarchy variables are technically retired - they are not available dimensions in Analysis Workspace, and will be going away when Reports & Analytics reaches its end-of-life date. I've also included this information on the hierarchy dimension page, and the `hier` implementation variable.
