### ISSUE TITLE
No ability to set listVar delimiter

### ISSUE THREAD

**Issue by stewartschillingsdi** [AdobeDocs/analytics.en#240]
Issue in ./help/implement/aep-edge/variable-mapping.md

The only allowed delimiter for list1-list3 is the comma (",").
Adobe Analytics allows you to configure this delimiter and many AA implementations are using delimiters other than commas.

I would suggest that (just as it was done for list props and hierarchies) a delimiter field be added to the schema (e.g. _experience.analytics.customDimensions.lists.list1.delimiter = "~") and respected in the automatic edge transformations.

**Comment by gigazelle** [comment]
Edge has been updated to automatically query the report suite settings and include the delimiter that Analytics expects. The docs have also been updated to reflect this information. Thanks for the report!
