### ISSUE TITLE
Exclude at beginning of sequence and Exclude at end of sequence use cases looks same

### ISSUE THREAD

**Issue by gkrish1001** [AdobeDocs/analytics.en#241]
Issue in ./help/components/segmentation/segmentation-workflow/seg-sequential-build.md

Exclude at beginning of sequence and Exclude at end of sequence use cases looks same. 

- Visitors who visited page A and did not visit page B.
- A restaurant wants to see inveterate users who avoid the main landing page and go directly to the Order Out page.

If the 2 different segments are solving the same use cases then what's the difference between those 2 segments?

**Comment by gigazelle** [comment]
Thanks for submitting this issue! The documentation has been updated to provide clearer examples for sequential segments using before and after criteria.
