### ISSUE TITLE
5-day processing latency - is it still true?

### ISSUE THREAD

**Issue by hmroczek** [AdobeDocs/analytics.en#243]
Issue in ./help/admin/c-server-call-usage/server-call-usage-dashboard.md

I have a case where the customer noticed 6-8 days of latency in their server call usage. I've consulted with T3 who claims that he has never seen processing latency lower than 5 days.

So is the "By default, is updated daily, with a 5-day processing latency." a norm, a default or average? If the latency is higher than 5 days is it an anomaly or it's working as intended?

Could you please provide more insight into this and if it's outdated, correct the article?

Best,

Hanna
<img width="871" alt="Screenshot 2022-10-19 at 14 18 09" src="https://user-images.githubusercontent.com/98605516/196702899-9a587c88-b112-4259-b20e-797732e6afea.png">

**Comment by MicaPete** [comment]
@hmroczek - according to the PM, the doc is correct. He suggests that the customer open a ticket with Customer Care.
