### ISSUE TITLE
london IP addresses not covered

### ISSUE THREAD

**Issue by krhoton-adobe** [AdobeDocs/analytics.en#244]
Issue in ./help/technotes/ip-addresses.md

"All of the ranges in this section are included in the above table."
The London 185.x addresses are not in the above table.

**Comment by gigazelle** [comment]
The London address is used for FTP, while the 'All' section is for data collection. However, acknowledging that it mentions that each individual block is included in the 'All' section, I'm talking with network engineering to see how we can better communicate this information. stay tuned!

**Comment by gigazelle** [comment]
Fixed with 243a6816a975438fead659568a2e5ec90ac6a394. Thanks!
