### ISSUE TITLE
export Activity Map context data variables through data feeds

### ISSUE THREAD

**Issue by Willian27Z** [AdobeDocs/analytics.en#245]
Issue in ./help/analyze/activity-map/activitymap-faq.md

Hello. In this doc it says that activity map context variables cannot be exported in data feed, but in the Data column reference it shows the clickmap columns are available: https://experienceleague.adobe.com/docs/analytics/export/analytics-data-feed/data-feed-contents/datafeeds-reference.html?lang=en

**Comment by gigazelle** [comment]
Good find! I've pushed a fix for the Activity Map FAQ. It will be live shortly.
