### ISSUE TITLE
Explanation of CNAME + RDC

### ISSUE THREAD

**Issue by alexbishop010** [AdobeDocs/analytics.en#249]
Issue in ./help/technotes/rdc/regional-data-collection.md

Documentation explains how RDC restriction is possible when using AppMeasurement. However, there is information missing which explains how CNAME can be used as part of Web SDK setup, in order to restrict edge locations that are used (i.e. EU only, NA only etc). Context is that a lot of customers ask the question "how can we ensure we only collect, process & store data in EU locations?". So this CNAME-based edge location restriction is a critical part of achieving that with CJA but currently it's not clear for customers that this is possible

**Comment by MicaPete** [comment]
Hi @alexbishop010 - here is your answer from the PM:
The RDC setup for Web SDK is identical to Analytics. Both use the same architecture to receive hits. The routing to AA or Konductor actually happens later. The RDC setup for Web SDK is identical to Analytics. Both use the same architecture to receive hits. The routing to AA or Konductor actually happens later.
The only difference is that there is no China RDC for Edge. That collection route is specific to Analytics.

I hope that helps.
