### ISSUE TITLE
Formula correction

### ISSUE THREAD

**Issue by bhatt-priyadutt** [AdobeDocs/analytics.en#253]
Issue in ./help/analyze/analysis-workspace/virtual-analyst/contribution-analysis/statistics-contribution-analysis.md

Hi, here in the formula's denominator, shouldnt there be `eai` instead of `ei` ?
![image](https://user-images.githubusercontent.com/68959880/209100805-3559b359-a0c1-4bf8-a280-5154fca4547b.png)

**Comment by MicaPete** [comment]
@bhatt-priyadutt - you are absolutely correct, it should be "eai". I've corrected this error. Thanks.

https://experienceleague.adobe.com/docs/analytics/analyze/analysis-workspace/virtual-analyst/contribution-analysis/statistics-contribution-analysis.html?lang=en
