### ISSUE TITLE
TRUE is not a JS primitive type

### ISSUE THREAD

**Issue by loldenburg** [AdobeDocs/analytics.en#256]
Issue in ./help/implement/vars/config-vars/collecthighentropyuseragenthints.md

In the docs, it says to set the variable to `TRUE`. But that is not a JS primitive type. So is it supposed to be `"TRUE"` or `true` ? Maybe Adobe can make this explicit to avoid developers having to trial-and-error.
s.collectHighEntropyUserAgentHints = TRUE

It would also help a lot if the expected changes to the HTTP requests to AA are documented here (which parameters will there be in addition?)

**Comment by gigazelle** [comment]
Thanks Lukas, I've addressed these points.

* You are correct, `true` is the correct syntax.
* Query parameters included start with a `h.` prefix. I've included this info in both the Client hints guide in technotes and in the query parameter table in the implementation guide.

**Comment by loldenburg** [comment]
Thanks @gigazelle, are the parameters sent in order to be used by Adobe's processing engine in some form or is there maybe even a way to surface the values to the interface (e.g. via Context Data)?
