### ISSUE TITLE
web.webPageDetails.errorPage or web.webPageDetails.isErrorPage

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/analytics.en#258]
Issue in ./help/implement/aep-edge/variable-mapping.md

The doc says "web.webPageDetails.errorPage | Flag that helps determine the ‘Pages Not Found’ dimension and metric." Where is this field coming from? Should this be web.webPageDetails.isErrorPage? I see that field in the AEP Web SDK ExperienceEvent field group. If it should be isErrorPage, please update the doc.

**Comment by MicaPete** [comment]
Thanks Daniel, @gigazelle will look into this.
