### ISSUE TITLE
A couple small issues in Segment Docs

### ISSUE THREAD

**Issue by bkfarnsworth** [AdobeDocs/analytics.en#26]
on this page: help/components/c-segmentation/seg-overview.md
(link: https://docs.adobe.com/content/help/en/analytics/components/segmentation/seg-overview.html)

This line needs a space after the OR:
`When building audience segments in the Segment Builder, you define conditions using the AND and ORoperators between containers.`

I couldn't really make sense of this sentence, maybe I am confused.
`Visit container where visit number equals 1: Viewing a Visit All page views from the first visit are included in the report because it matches the segment rule.`

This sentence doesn't make sense - a dimension can't require a persistent dimension.  Should it be the Participation model requires a persistent dimension? 
`If using a Revenue Participation report, no pages receive credit because this dimension requires a persistent dimension. `

**Comment by gigazelle** [comment]
Thanks very much! It appears this was fixed shortly after you raised the issue. We appreciate you bringing it to our attention!
