### ISSUE TITLE
EMEA Datacenters listed for Adobe Analytics Data

### ISSUE THREAD

**Issue by StrawberryBe** [AdobeDocs/analytics.en#260]
Issue in ./help/technotes/privacy-overview.md

I was under the impression that AA data is hosten in our UK datacenter, the privacy-overview states though it is also hosted on the Amsterdam datacenter (which is true for CJA). I think the wording is confusing: If it is for Analytics data in general it is correct, if it is for Adobe Analytics data it is not AFAIK as of Feb 2023. [Link to highlight](https://experienceleague.adobe.com/docs/analytics/technotes/privacy-overview.html?lang=en#:~:text=Certifications-,AMS1,-Luttenbergweg%204)

**Comment by MicaPete** [comment]
You are correct, and I have deleted the AMS datacenter. Thank you.
