### ISSUE TITLE
Consider adding a column for field group

### ISSUE THREAD

**Issue by mugdoor** [AdobeDocs/analytics.en#261]
Issue in ./help/implement/aep-edge/variable-mapping.md

I'm just wondering if it might be helpful here to have another column that shows which field groups these items are in. If there is somewhere else where that is laid out, let me know, but I think somewhere we have to let people know which field groups they should add to their schema if they are going to push data back to Analytics when using the Web SDK.
Thanks,
Doug Moore

**Comment by gigazelle** [comment]
They should all be in the 'Adobe Analytics ExperienceEvent Template' field group. I've added that information to the top of the page.
