### ISSUE TITLE
Example references _ppvInitialPercent, should be _ppvInitialPercentViewed

### ISSUE THREAD

**Issue by jkunz** [AdobeDocs/analytics.en#263]
Issue in ./help/implement/vars/plugins/getpercentpageviewed.md

The examples, as written, caused JS errors that prevented beacons from firing. After digging in, I found the issue:  _ppvInitialPercent, should be _ppvInitialPercentViewed

**Comment by MicaPete** [comment]
Hi @jkunz - thanks for noticing - this has been fixed.
https://experienceleague.adobe.com/docs/analytics/implementation/vars/plugins/getpercentpageviewed.html
