### ISSUE TITLE
Admins can no longer change their access rights to a project (which is inexplicable product design btw...)

### ISSUE THREAD

**Issue by loldenburg** [AdobeDocs/analytics.en#265]
Issue in ./help/analyze/analysis-workspace/curate-share/share-projects.md

The text reads:
"<html>
<body>

As an admin, what project experience will I see? | Admins placed in a Can duplicate or Can view role will receive those limited experiences when they open a project. If desired, an Admin can increase their role to Can edit at anytime through Components > Projects.
-- | --

</body>
</html>"
But that view does not exist anymore. Even if I am an Admin, I can no longer change projects of others if they have not given me edit rights. I can do the same if they have given me no rights. I will never get that, and it does not make sense. And it is a nuisance and a compliance issue, as things that need to be changed (because people go on vacation, reports break and need to be updated, people put stuff in shared workspaces that should not be in there etc...).

**Comment by luke-penrod** [comment]
Thanks for your comment! My tests show that you are indeed correct. Before I update the documentation, I'm following up with our PM team to ensure that this was an intended functionality change.

**Comment by loldenburg** [comment]
This is a grave oversight by the product team. We waste so much time when
we get links to workspaces that we should assist with, then we do changes
in them, then we want to save and see that we cannot do it because the
workspace is shared with "Save As" rights only. Even though we are Admins.
Even better when the owner of that workspace is currently on vacation. This
is just a nuisance for Admins.
Also it is a compliance issue. If somebody puts data that is not allowed to
go to some people into a Workspace and that workspace goes to these people
eg as a PDF, we need to be able to quickly change things in that workspace.
Right now, we cannot if that person cannot be reached, has left the
company, is sick or on vacation. We have to change the owner first
tediously via "Migrate Assets", do the changes, and then migrate the asset
back to the original owner... This is soooo freaking time-consuming. Please
let Product Team know that this can NOT be "as designed".

**Comment by luke-penrod** [comment]
Yes, great points. I just spoke with our engineering team, and this is indeed a bug that we will fix. 

That said, the workflow for the steps that an admin needs to take in order to change their role from View to Edit did change, so I will update the documentation now to reflect that updated workflow. And I'll assign the bug to the dev team. As of now, they are aware of it.
