### ISSUE TITLE
Broken embed of a video

### ISSUE THREAD

**Issue by mugdoor** [AdobeDocs/analytics.en#270]
Issue in ./help/analyze/analysis-workspace/c-panels/average-minute-audience-panel.md

Hi you guys.
On this page, you can see that there is a broken embed of a video. Inspecting it, it looks like maybe it has comment codes around it or something.
The markdown embed code for the video should be:
>[!VIDEO](https://video.tv.adobe.com/v/330177/?quality=12&learn=on)

If you have any questions, let me know.
Doug Moore
domoore@adobe.com

**Comment by ridmaur** [comment]
Hey Doug, couldn't see the issue. Maybe it's solved already by someone else? Can you check and if you think it is solved, close the issue? 

Thanks.
[rmaur@adobe.com](mailto:rmaur@adobe.coml)

**Comment by MicaPete** [comment]
Doug, Luke fixed this, so I will close it.
