### ISSUE TITLE
Wrong XDM path for the transactionID field.

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/analytics.en#273]
This page is reporting the following:
"Transaction ID is [mapped for Adobe Analytics](https://experienceleague.adobe.com/docs/analytics/implementation/aep-edge/variable-mapping.html?lang=en) under the XDM field commerce.order.transactionID."

Actually the Commerce FG does not feature such a path.
In fact the referred document is reporting the following path:

`commerce.order.payments[0].transactionID`

Could you please correct?

Thanks
Alberto

Issue in ./help/implement/vars/page-vars/transactionid.md

**Comment by gigazelle** [comment]
Fixed - thank you for bringing it to our attention!
