### ISSUE TITLE
Comparing segments

### ISSUE THREAD

**Issue by SJW-ecxio** [AdobeDocs/analytics.en#274]
Issue in ./help/analyze/analysis-workspace/visualizations/fallout/compare-segments-fallout.md

In the video it says you can compare up to three segments in fallout analysis whereas it is unlimited as stated in the documentation.
Not a problem, however it was one of the renewal exam questions (that I got wrong :D)

**Comment by MicaPete** [comment]
I added a clarification that states that the video content regarding the number of segments you can compare is incorrect. Unfortunately, we cannot get a new video on this topic produced at this time.
