### ISSUE TITLE
Nonsensical steps

### ISSUE THREAD

**Issue by alibrahi** [AdobeDocs/analytics.en#275]
Issue in ./help/components/classifications/importer/processing-time.md

These steps don't make sense and don't lead anywhere:

If you want to see if a classification file is finished, do the following:

Log in to Adobe Analytics, then navigate to Admin > Classification importer.

Select the report suite and data set in question.

If processing is not yet complete, either one of the following messages appear:

Notice The selected report has a classification import that is processing.
Notice The selected report has classification data that hasn’t propagated to all servers yet.

**Comment by gigazelle** [comment]
Hi there! Can you please elaborate around what doesn't make sense about that statement? If you navigate to that part of the UI. the presence of the message indicates that processing is not complete. If there is no message, then the processing is complete.

**Comment by alibrahi** [comment]
Hi Russ!

So there are no steps to get to either of those messages:

Admin -> Classification Importer

Enter report suite and classification data where?

[cid:423cb993-f2de-4cc5-9e1d-79010f03ceb1]

There are 4 tabs and none of them result in these steps:

[cid:a67f188c-b0dd-491e-9eee-9df4ad825239]

Sincerely,

Ali


***@***.***?anonymous&ep=bwmEmailSignature>              Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________

**Comment by gigazelle** [comment]
It's right here:

![image](https://github.com/AdobeDocs/analytics.en/assets/33764851/32ad3803-6f7d-453e-b34c-5b2934a8e79a)

If it's still processing, there's a big yellow bar that appears with the abovementioned notifications.

**Comment by gigazelle** [comment]
Hi there, let me know if there's anything else that can use additional explanation, or if you have recommendations on how to reword the docs so that they make more sense!

**Comment by alibrahi** [comment]
Hi Russ!

Will do, thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
