### ISSUE TITLE
Broken Link to Analytics Health Dashboard

### ISSUE THREAD

**Issue by GradyCongdon** [AdobeDocs/analytics.en#278]
Issue in ./help/implement/review/focused-review.md

The link for the _Analytics Health Dashboard_ appears to be broken in the "Make sure that your KPI metrics and variables still function well" section:

> Re-run the [Analytics Health Dashboard](https://assets.adobe.com/public/9549dbe7-765a-4899-77b8-85cbba1a4252) to monitor broad trends of your KPI metrics and variables.

**Comment by MicaPete** [comment]
This issue has been fixed. Thanks for bringing it to our attention.
