### ISSUE TITLE
Clarification needed for "unspecified" reporting

### ISSUE THREAD

**Issue by jklockow** [AdobeDocs/analytics.en#28]
Issue in help/technotes/unspecified.md

The following passage from this page may need to be clarified based on some client feedback I got. Workspace now uses the term "breakdown" to apply to correlations as well. I believe "breakdown" used to just apply to traffic variables, in which case, the passage  below makes sense. However, eVars can be persisted to hits where they aren't actually set in the image request. Suggest we add "or persisted from a previous hit" after "not seen" below.

_Breakdown reports where only one variable fired: When you apply a breakdown to a variable, every instance of that variable must be accounted for. If the second variable was not seen, the dimension value is 'Unspecified'._

**Comment by MicaPete** [comment]
https://docs.adobe.com/content/help/en/analytics/technotes/unspecified.html

**Comment by jklockow** [comment]
Hi,

The edit on this is actually incorrect. Sorry if my suggestion was unclear. I think the full sentence should read:

If the second variable was not seen or persisted from a previous hit, the dimension value is 'Unspecified'.

The key distinction is that the value will be unspecified if the variable was not seen and/or NOT persisted from a previous hit. I’m assuming the reader will read the not as applying both to seen and persisted. If you think that’s not clear, then maybe the sentence needs a more complete restructuring.

Thanks.
