### ISSUE TITLE
performance.timing is deprecated

### ISSUE THREAD

**Issue by jsanders-heydrumline** [AdobeDocs/analytics.en#281]
Issue in ./help/implement/vars/plugins/getpageloadtime.md

This plugin code utilizes the `performance.timing` method, which according to MDN has been deprecated. https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming

**Comment by MicaPete** [comment]
@jsanders-heydrumline  - thanks for alerting us to this. After verifying with the SME, we are now indicating in the documentation that this plugin is no longer supported.

**Comment by jsanders-heydrumline** [comment]
Thanks for the update.

Will there be a replacement plugin at some point that utilizes the new PerformanceNavigationTiming interface?

**Comment by MicaPete** [comment]
Expect an updated plugin in about a month.
