### ISSUE TITLE
Issue in getTimeSinceLastVisit plugin

### ISSUE THREAD

**Issue by NatalliaBelavusavaTR** [AdobeDocs/analytics.en#282]
`getTimeSinceLastVisit` plugin function, provided in documentation, always returns `"New Visitor"` and set `"s_inv"` to `"0"` 
After the first visit `s_inv` cookie is set to `"0"` and every next revisit `l` is set to `"0"` in `(l = cookieRead("s_inv"))` and `s_inv` is set back to `"0"`  in `cookieWrite("s_inv", l, 30)`

condition `"0" !== l` is never fulfilled
```jsx
return n
  ? 1800 < l || cookieRead("s_inv")
    ? (cookieRead("s_inv") && (l = cookieRead("s_inv")),
      cookieWrite("s_inv", l, 30),
      "0" !== l ? formatTime(l) : "New Visitor")
    : ""
  : (cookieWrite("s_inv", "0", 30), "New Visitor");

```
https://experienceleague.adobe.com/docs/analytics/implementation/vars/plugins/gettimesincelastvisit.html?lang=en

**Comment by NatalliaBelavusavaTR** [comment]
The value changes only after 30 minutes of inactivity, probably this should be reflected in documentation

**Comment by MicaPete** [comment]
@NatalliaBelavusavaTR - we are looking into this. Thank you for your patience.

**Comment by MicaPete** [comment]
Hi @NatalliaBelavusavaTR - according to the developer: "The logic still works.  If the user below can reproduce an error with the plugin (i.e. prove through testing that there’s a problem), then please have them provide the exact steps they took to reproduce."
