### ISSUE TITLE
The "unsupported elements" link is broken

### ISSUE THREAD

**Issue by bgundersen** [AdobeDocs/analytics.en#285]
Issue in ./help/admin/admin/component-migration/component-migration.md

The link to unspported elements doesn't take you anywhere. Is that supposed to go to this page? https://experienceleague.adobe.com/docs/analytics/admin/admin-tools/component-migration/prepare-component-migration.html?lang=en

**Comment by MicaPete** [comment]
This link has been fixed. Thanks for bringing it to our attention.
