### ISSUE TITLE
Correct in Data sources FAQ doc

### ISSUE THREAD

**Issue by shrutpradhan** [AdobeDocs/analytics.en#286]
Issue in ./help/import/data-sources/faq.md

 Can I delete data that was imported using data sources?
Yes, we should be using data repair API. It is written in the doc that we can't which is wrong.

**Comment by MicaPete** [comment]
Thanks, we have corrected this error: https://experienceleague.corp.adobe.com/docs/analytics/import/data-sources/faq.html
