### ISSUE TITLE
Video load time is abysmal

### ISSUE THREAD

**Issue by Cosmas47** [AdobeDocs/analytics.en#288]
Issue in ./help/analyze/analysis-workspace/curate-share/share-projects.md

Video loading/buffering on Low quality settings very poor and I'm on a gigabit fiber connection. It took twice as long to view the video because I had to wait for it to chug along loading in because apparently it won't buffer while paused. Poor experience overall.

**Comment by MicaPete** [comment]
I've informed the person in charge of creating videos.

**Comment by mugdoor** [comment]
I've tested it, and I am not seeing the issue that you are describing. Can you tell me:
* Is the video still having the issue?
* Are other videos having the same issue? For example, try any number of videos from the left hand navigation on this tutorials page: https://experienceleague.adobe.com/en/docs/analytics-learn/tutorials/overview
* Do you have other people on the same internet connection as you are, and do they see the same problem?
* If it is having the problem right now, can you run a speedtest on your computer and verify that there is nothing wrong there?

Thanks for your help running down this issue.
Doug Moore
