### ISSUE TITLE
2 differente infos on 2 pages.

### ISSUE THREAD

**Issue by ericthibeault-adobe** [AdobeDocs/analytics.en#289]
On https://experienceleague.adobe.com/en/docs/analytics/admin/admin-tools/component-migration/component-migration it says that "any mapping cannot be modified once migration is completed"
but on https://experienceleague.adobe.com/en/docs/analytics/admin/admin-tools/component-migration/prepare-component-migration it also says that "these mappings cannot be modified or undone EXCEPT by contacting Customer Care."

Of course we don’t want to push customers to do whatever and then ask CC for help, but still both pages are not telling the same thing.

**Comment by luke-penrod** [comment]
Thanks for calling this to our attention! We've updated the content to make these two descriptions consistent with the following information:
"Any mappings made on one project apply to all future projects across your entire IMS org, regardless of which user is performing the migration. These mappings cannot be modified or undone except by contacting Customer Care."
