### ISSUE TITLE
Extra characters in examples

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/analytics.en#29]
Issue in help/implement/js-implementation/function-tl.md

The following two sections contain examples that look like it has extra characters not intended to be there. Please confirm.

```
useForcedLinkTracking
...
Example: s.useForcedLinkTracking& = false

forcedLinkTrackingTimeout
...
Example: s.forcedLinkTrackingTimeout&nbsp;=&nbsp;500
```

**Comment by gigazelle** [comment]
Thanks very much for pointing this out! It will be fixed and published later today.
