### ISSUE TITLE
Screenshots not showing up on prod

### ISSUE THREAD

**Issue by antonioatadobe** [AdobeDocs/analytics.en#291]
Issue in ./help/analyze/report-builder/setup/upgrade-arb.md
Check out the live page at https://experienceleague.adobe.com/en/docs/analytics/analyze/report-builder/report-builder-setup/upgrade-arb
The screenshots are broken.

**Comment by MicaPete** [comment]
Hi @antonioatadobe - there will be a brand new version of Report Builder in the September time frame and this existing documentation will be EOL'd. So I will wait to update the screenshots once I have the full UI at my disposal.

**Comment by MicaPete** [comment]
Delayed to October.
