### ISSUE TITLE
The note for email account type is wrong

### ISSUE THREAD

**Issue by immany** [AdobeDocs/analytics.en#295]
Issue in ./help/components/locations/configure-import-accounts.md

The following note for Email account type is wrong. Email account can be used only with Data Warehouse.
NOTE
Email accounts can be used only with [Data Feeds](https://experienceleague.adobe.com/en/docs/analytics/export/analytics-data-feed/create-feed). (Email accounts are not supported with [Data Warehouse](https://experienceleague.adobe.com/en/docs/analytics/export/data-warehouse/dw-create-request/dw-request-report-destinations) or [Classification sets](https://experienceleague.adobe.com/en/docs/analytics/components/classifications/sets/overview)).

**Comment by luke-penrod** [comment]
@immany - Thanks for your feedback and for catching this error. I've updated the source docs with the correction. The changes will be published to Experience League shortly. 

Thanks for helping to improve the Analytics documentation!
