### ISSUE TITLE
Conversion variables table incorrectly formatted

### ISSUE THREAD

**Issue by pmonjo** [AdobeDocs/analytics.en#296]
Issue in ./help/admin/admin/c-manage-report-suites/c-edit-report-suites/general/c-processing-rules/processing-rule-dimensions.md

The table that should be shown below [Conversion variables](https://experienceleague.adobe.com/en/docs/analytics/admin/admin-tools/manage-report-suites/edit-report-suite/report-suite-general/c-processing-rules/c-processing-rules-configuration/processing-rule-dimensions#conversion-variables) has not been correctly converted from Markdown to HTML.

**Comment by MicaPete** [comment]
Thank you, this has been fixed.
https://experienceleague.adobe.com/en/docs/analytics/admin/admin-tools/manage-report-suites/edit-report-suite/report-suite-general/c-processing-rules/c-processing-rules-configuration/processing-rule-dimensions#conversion-variables
