### ISSUE TITLE
head anchor code is showing. 

### ISSUE THREAD

**Issue by antonioatadobe** [AdobeDocs/analytics.en#298]
Issue in ./help/components/vrs/vrs-about.md

All anchor coding is showing as text.
![image](https://github.com/user-attachments/assets/427dd7a7-c93e-4762-8c56-6445bceafef2)

**Comment by antonioatadobe** [comment]
Also on this one: /en/docs/analytics/admin/admin-tools/manage-report-suites/report-suites-admin

**Comment by MicaPete** [comment]
@antonioatadobe - this was a system-wide problem that has since been resolved.

**Comment by antonioatadobe** [comment]
@MicaPete just saw the post about the issue this morning. Sorry for the false alarm and thanks for the follow-up.
