### ISSUE TITLE
Error in example?

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/analytics.en#30]
Hello,

Please confirm if this code is correct. I believe there might be an error due to copy/paste.

```
<a href="./popup.html" target="_blank" onClick="<a href="./popup.html" onclick="s.tl(this,'o','popup',null,'navigate');javascript:window.open('./popup.html','popup','width=550,height=450'); 
return false;">
```

**Comment by MicaPete** [comment]
@justlee-adobe  - please specify the file where you found this.

**Comment by justlee-adobe** [comment]
On this page: https://docs.adobe.com/content/help/en/analytics/implementation/javascript-implementation/function-tl.html

In this section: "Popup Windows with useForcedLinkTracking"

**Comment by gigazelle** [comment]
Thanks for your feedback - this has been fixed.
