### ISSUE TITLE
Need help understanding examples

### ISSUE THREAD

**Issue by justlee-adobe** [AdobeDocs/analytics.en#31]
![Screen Shot 2019-08-17 at 8 00 50 PM](https://user-images.githubusercontent.com/50026956/63218474-ddc4e880-c129-11e9-9ac7-a0243a574dd2.png)

I don't understand why the mysuite2 would receive the data in the example provided since the path that the example is based on is "path1" and the mysuite2=path2.

Also, not clear on "mysuit1=path5" example also and why data would go into mysuit1 if the sample is based on "path1".

**Comment by MicaPete** [comment]
@gigazelle - can you take a look at this?

**Comment by gigazelle** [comment]
I've rewritten this page, and included much better code examples. Should be published live by tomorrow.

Thanks for pointing this out!
