### ISSUE TITLE
Several (incorrect) References to eVarn

### ISSUE THREAD

**Issue by kirkman-adbe** [AdobeDocs/analytics.en#32]
Issue in help/import/c-data-sources/c-datasrc-types/datasrc-transactionid.md

**Comment by MicaPete** [comment]
@kirkman-adbe  - can you be more specific as to what needs to be changed, please?

**Comment by kirkman-adbe** [comment]
the variable syntax is "eVar" - I believe the intent for this page was to represent as "eVarN"

**Comment by kirkman-adbe** [comment]
Alternate page for reference:
https://docs.adobe.com/content/help/en/analytics/implementation/javascript-implementation/variables-analytics-reporting/vars-limitiations.html

**Comment by MicaPete** [comment]
https://docs.adobe.com/content/help/en/analytics/import/data-sources/data-types-and-categories/datasrc-transactionid.html
