### ISSUE TITLE
Outdated References in Document

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics.en#35]
Issue in help/admin/user-management2/c-customize-report-access/groups-analytics-tools.md

The following permissions are documented on this page but no longer available in the Experience Cloud:

**Analytics Tools**
Announcements
Billing
ClickMap
Create / Curate Project in Analysis Workspace
P3P Policy

**Classifications Manager**
Announcements

As appropriate, these should be deleted from the documentation.

**Comment by MicaPete** [comment]
Fixed
