### ISSUE TITLE
Document References Deprecated Feature

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics.en#36]
Issue in help/analyze/analysis-workspace/curate-share/curate.md

The highlighted portion of this instruction references a deprecated permission:

"Before creating or curating an Analysis Workspace project, administrators must add you to a group with the **Create / Curate Projects** in Analysis Workspace permission enabled"

The correct permission now is the "Analysis Workspace Access".

**Comment by MicaPete** [comment]
Fixed
