### ISSUE TITLE
page_event missing lookup

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics.en#37]
Issue in help/export/analytics-data-feed/c-df-contents/datafeeds-reference.md

The current description for page_event is not detailed enough. It should reference the entire lookup for this dimension.

**Comment by MicaPete** [comment]
@gigazelle - can you take a look at this?

**Comment by gigazelle** [comment]
Thanks - right next to the column reference page, there is the page event lookup page: https://docs.adobe.com/content/help/en/analytics/export/analytics-data-feed/data-feed-contents/datafeeds-page-event.html

I'll add a link to the row in the column reference to link to this page. Thanks for pointing this out!
