### ISSUE TITLE
Release notes out of date

### ISSUE THREAD

**Issue by mpspencer** [AdobeDocs/analytics.en#38]
Issue in help/implement/appmeasurement-release-notes/c-release-notes-android.md

Release notes out of date as latest SDK version is Android 4.17.9

**Comment by gigazelle** [comment]
Thanks for letting us know about this!

The AppMeasurement release notes in that section are for the 4.x libraries, and not the current SDK's located here: https://aep-sdks.gitbook.io/docs/ - as far as I know, 4.13.4 was the last 4.x version.

The doc team here is working to figure out what we are going to do with these pages, and how we want to point users to the latest and greatest without eliminating potentially valuable information about versions no longer updated. We have this logged internally, so we will get this taken care of once we determine how to proceed.
