### ISSUE TITLE
Add an example for "Set multiple variables in a single rule"

### ISSUE THREAD

**Issue by bgundersen** [AdobeDocs/analytics.en#40]
Issue in help/admin/admin/c-processing-rules/processing-rules-examples/processing-rules-examples.md

Because there is a limit of 150 rules, customers wonder how they can set 250 variables. Conditional statements allow you to do this: overwrite eVar2 with contextData.section _if_ contextData.section is set.
You can have dozens of conditional statements in a single rule.

It would be good to show an example. This might also be mentioned in the tips and tricks section.
<img width="1013" alt="image001" src="https://user-images.githubusercontent.com/15787841/65267365-157cd280-dad2-11e9-85ae-a8287f842778.png">

**Comment by gigazelle** [comment]
Thanks Bret! I've rewritten the following page to accommodate your recommendation: https://docs.adobe.com/content/help/en/analytics/admin/admin-tools/processing-rules/processing-rules-examples/processing-rules-copy-context-data.html

It should be published live by tomorrow.
