### ISSUE TITLE
Link to Confidence is 404

### ISSUE THREAD

**Issue by quandvdo** [AdobeDocs/analytics.en#44]
Issue in help/components/c-variables/dimensionslist/report-target-lift-confidence.md

Link to Confidence is 404 
https://marketing.adobe.com/resources/help/en_US/rec/c_Confidence_Level_and_Confidence_Interval.html

**Comment by MicaPete** [comment]
We will put in a redirect to this page: https://docs.adobe.com/help/en/target/using/reports/settings/average-lift-bounds-and-confidence-interval.html
