### ISSUE TITLE
Formatting error in 'Syntax' section (under "Implementing Using Product Syntax")

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#45]
Issue in help/components/c-variables/c-merch-variables/var-merchandising-impl.md

Some of the formatting code (e.g., "codeph") is shown as content in the first 'Syntax' block on the page; this is in the section titled "Implementing Using Product Syntax".

**Comment by MicaPete** [comment]
@gigazelle - can you look into this, please?

**Comment by gigazelle** [comment]
Thank you @inselaffe for bringing this up! I've published a fix for this, which should be live within a day or so.
