### ISSUE TITLE
Configuration details don't include 2020

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#46]
Issue in help/implement/js-implementation/plugins/gettimeparting.md

The configuration details for the three Daylight Saving Time zones only extend to 2019; they should be extended to cover 2020 and 2021.

**Comment by MicaPete** [comment]
Thanks for your comment. This page is now updated.
https://docs.adobe.com/content/help/en/analytics/implementation/javascript-implementation/plugins/gettimeparting.html
