### ISSUE TITLE
HTML elements in syntax example

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#47]
Issue in help/implement/js-implementation/event-purchase.md

The syntax example includes HTML elements (e.g., "<b>").

**Comment by MicaPete** [comment]
@gigazelle - can you look into this?

**Comment by gigazelle** [comment]
Thanks @inselaffe for raising this! I've updated the article so it no longer has HTML stuff in the example. Should be published by tomorrow.
