### ISSUE TITLE
Interface Language Instructions Out of Date

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/analytics.en#48]
Issue in help/analyze/reports-analytics/getting-started.md

Currently, this document instructs users to change the UI language by "Click the View In menu, then click a language:" Changing the language is now set through the footer. The user simply has to click the active language to be given a list of alternative languages.

**Comment by MicaPete** [comment]
@jtwood426, thanks for helping us improve our documentation. This issue has now been fixed.

https://docs.adobe.com/content/help/en/analytics/analyze/reports-analytics/getting-started.html
