### ISSUE TITLE
Missing details for mobile_code

### ISSUE THREAD

**Issue by dustinw1980** [AdobeDocs/analytics.en#49]
Issue in help/export/analytics-data-feed/c-df-contents/datafeeds-reference.md

A customer has pointed out that mobile_code is missing from this list.

**Comment by dustinw1980** [comment]
Actually looks like mobile_code isn't available in data feeds. I'm not sure where the customer is seeing this. This can probably be closed.

**Comment by gigazelle** [comment]
Thanks Dustin. You are correct that mobile_code is not an available column in data feeds. It could be something custom created by the customer or Adobe, though.
