### ISSUE TITLE
Use of "10MM" is not clear

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#5]
Issue in help/components/c-classifications2/crb/classification-rule-builder.md

It is not made clear that "10MM" refers to 10,000,000 - this is potentially business/finance jargon, the meaning of which is not going to be obvious to every reader.

**Comment by MicaPete** [comment]
I clarified this to say "10 million". Thanks for your comment. I will close this issue once the document has been re-published.
