### ISSUE TITLE
Are Segments published to Experience Cloud avail for activation? 

### ISSUE THREAD

**Issue by mattsmedley** [AdobeDocs/analytics.en#50]
Issue in help/components/c-segmentation/c-segmentation-workflow/seg-publish.md

Should the list of products include Adobe Campaign in the first sentence? 

> Publishing a segment to the Experience Cloud lets you use the segment for marketing activity in the **Audience Library, Target, Audience Manager, and Advertising Cloud**. 

I'm thinking this should read:

Publishing a segment to the Experience Cloud lets you use the segment for marketing activity in the Audience Library, **_Campaign_**, Target, Audience Manager, and Advertising Cloud. 

Please confirm.

**Comment by MicaPete** [comment]
@mattsmedley - I will add Campaign. The only tricky part is that Campaign has an additional 24 hour latency on top of the now 8 hour latency, so they don’t perform the same as all the other solutions.

**Comment by mattsmedley** [comment]
Ahh….  Might be good to call out…
Is that the same whether Classic or Standard?

Matt Smedley  |  Cloud SC  |  Adobe  |  c. 949.981.2831  |  msmedley@adobe.com

.

**Comment by MicaPete** [comment]
@mattsmedley  - I have added this information to the topic and it should be published within 3-4 hours. (And yes, it is the same whether Classic or Standard).
