### ISSUE TITLE
resolution.tsv lookup table not exist in documents

### ISSUE THREAD

**Issue by ibozkurt79** [AdobeDocs/analytics.en#51]
Issue in help/export/analytics-data-feed/c-df-contents/datafeeds-reference.md

I couldn't locate the file for resolution id resolution.tsv lookup table in the resolution field

**Comment by MicaPete** [comment]
@gigazelle  - can you look into this, please?

**Comment by gigazelle** [comment]
Hi @ibozkurt79 - I'm looking at a data feed file downloaded on my end, and located resolution.tsv right inside the zipped file. Is this a documentation issue, or is it potentially an issue that you'll want to open with customer care?

**Comment by ibozkurt79** [comment]
this is a documentation issue. I am trying to translate the resloution_id since it might be either browser resloution (height, width) or screen resolution

**Comment by gigazelle** [comment]
The column resolution_id is not valid for feeds created in the Analytics UI. If you log in to Analytics then go to Admin > Data Feeds, when creating a data feed you can see all available columns.

Can you share more information on where the data feed or the resolution_id column originated from? We might be able to point you in the right direction from there.

**Comment by ibozkurt79** [comment]
I have resolution_id column in my site_catalyst table. 
is connected device screen height or width included in the site catalyst feed or is it only browser height?  if it is only browser height, is it changeable by enlarging or minimizing the browser?
That is the question I am trying to understand

**Comment by ibozkurt79** [comment]
Resolution id appears like '1024X 533' and named as screen resolution_id. Is it relevant with adobe feed?

**Comment by gigazelle** [comment]
it's not part of the default columns adobe provides, but you can probably determine what it is by comparing those values with other available columns.

The `browser_height` and `browser_width` columns are the visible area of your site, and can be changed by resizing the window. The `s_resolution` column is monitor height and width, and cannot be changed by resizing the browser. You could compare your resolution_id column with these other columns to determine what type of resolution it is measuring.

**Comment by ibozkurt79** [comment]
Thank you. I think my issue is resolved
