### ISSUE TITLE
The link for "Livestream Overview" redirects to "https://www.adobe.io/" page

### ISSUE THREAD

**Issue by gclausen** [AdobeDocs/analytics.en#52]
Issue in help/analyze/c-reporting-api/api-comparison.md

The "Livestream Overview" link on this page https://docs.adobe.com/help/en/analytics/analyze/c-reporting-api/api-comparison.html points to https://marketing.adobe.com/developer/documentation/analytics-live-stream/overview-1%E2%80%8B but it redirects to https://www.adobe.io/

**Comment by MicaPete** [comment]
@gclausen   - as far as I know, the Livestream API is no longer supported, but I can find out. Does this help: https://helpx.adobe.com/analytics/kb/getting-started-with-livestream-api.html

**Comment by MicaPete** [comment]
@gclausen - and this:
https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/live-stream-api/index.md

**Comment by MicaPete** [comment]
@gclausen  - please ignore the part about the Livestream API is no longer being supported. I was mistaken.
