### ISSUE TITLE
Formatting errors

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#54]
Issue in help/implement/c-implement-with-dtm/c-aa-tool/cookies-analytics.md

Page formatting after opening paragraph resulting in garbled text.

**Comment by gigazelle** [comment]
https://docs.adobe.com/content/help/en/analytics/implementation/implement-analytics-with-dtm/analytics-tool/cookies-analytics.html

This appears to be fixed. Please let me know if you're still seeing issues.
