### ISSUE TITLE
Please review step 7 of the impl-acceptance.md

### ISSUE THREAD

**Issue by deyu-w** [AdobeDocs/analytics.en#55]
Issue in help/implement/impl-testing/impl-validation/impl-acceptance.md

Hi team,

I'm a technical consultant based in Sydney, Australia. A client is asking me to enable the Implementation Verification certification mentioned at step 7 of the doc above. After checking with other consultants, it seems nobody knows what it means. Could you check where it's from and if it's still valid? Thanks.

"7. After the acceptance has been received, the Adobe Consultant enables the Adobe Best Practices - Implementation Verification certification within the interface."

**Comment by gigazelle** [comment]
Thanks - it is now tracked internally as AN-198902. Feel free to contribute to Jira there.
