### ISSUE TITLE
What happens when sendBeacon API isn't supported?

### ISSUE THREAD

**Issue by arobsco** [AdobeDocs/analytics.en#56]
Issue in help/implement/js-implementation/c-variables/config-vars/s-usebeacon.md

Can this documentation be expanded to cover what happens when the sendBeacon API isn't supported/available? Does AppMeasurement fallback to normal send methods?

**Comment by gigazelle** [comment]
Talking with our implementation product manager about this one. I'll update the docs once I hear back.

**Comment by dancingcactus** [comment]
@gigazelle and @arobsco AppMeasurement will check to see if sednBeacon is supported. If it isn't it will revert back to the normal methods of transmission.

**Comment by gigazelle** [comment]
I've added this content to the `useBeacon` page: https://docs.adobe.com/content/help/en/analytics/implementation/vars/config-vars/usebeacon.html
