### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Lorriex** [AdobeDocs/analytics.en#58]
Issue in help/import/c-data-sources/datasrc-how-data-sources-works.md

This link: 
See Data Sources API Documentation . 
is broken. it goes to a non-existent directory:  https://marketing.adobe.com/developer/documentation/data-sources/c-data-sources-api

please fix the link, i need that document!

**Comment by MicaPete** [comment]
This link has been fixed. Thanks for submitting the issue.
