### ISSUE TITLE
Add more information about "Delay Processing"

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/analytics.en#59]
Issue in help/export/analytics-data-feed/c-data-feed-actions/r-feed-information.md

Please provide a more complete explanation of what the "Delay Processing" feature does, and what the effects are? Does it improve data accuracy because the processing is given more time to include late arriving hits? Is this the same as 

https://docs.adobe.com/content/help/en/analytics/export/analytics-data-feed/data-feed-contents/late-arriving-hits.html

**Comment by gigazelle** [comment]
Thanks for raising this issue! I've added more information to delay processing, and will have it published later today.
