### ISSUE TITLE
Code sample formatting is broken

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#60]
Issue in help/implement/js-implementation/c-additional-libraries/samplecode.md

Search for "codeph" inside the code snippet titled "Example 1"

**Comment by gigazelle** [comment]
These pages have been removed since they were outdated. The left nav has also been updated to make more sense when implementing Analytics: https://docs.adobe.com/content/help/en/analytics/implementation/home.html

Thanks!
