### ISSUE TITLE
Installation should be via launch

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/analytics.en#62]
Issue in help/implement/js-implementation/plugins/getnewrepeat.md

The plugin is available with the Launch extension "[Common Analytics Plugins](https://exchange.adobe.com/experiencecloud.details.102744.common-analytics-plugins.html)". The document should call this out and the launch extension installation should be the recommended way.

**Comment by gigazelle** [comment]
Thanks for your feedback! We've listed all plug-ins and how to install them through Launch. https://docs.adobe.com/content/help/en/analytics/implementation/vars/plugins/impl-plugins.html
