### ISSUE TITLE
/analytics/analyze/analysis-workspace/attribution-iq.html

### ISSUE THREAD

**Issue by tgiffin** [AdobeDocs/analytics.en#63]
Issue in help/analyze/analysis-workspace/c-panels/attribution/attribution.md
This page is not showing up when you click on any link for several different locations.  I tried 2 different browsers and the page doesn't even have a 404. https://docs.adobe.com/content/help/en/analytics/analyze/analysis-workspace/attribution-iq.html

**Comment by MicaPete** [comment]
This has been fixed, thanks for your feedback.
