### ISSUE TITLE
Garbled article

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#64]
Issue in help/implement/js-implementation/c-additional-libraries/otherreq.md

Article appears to be missing some content, and other content is repeated:
1. Article refers to sample code and a sample URL that do not appear
2. The third bullet-point (under "Secure (<https:> vs. Non-Secure (<http:>) Image Requests") is a partial repetition of the first one

**Comment by gigazelle** [comment]
Thanks for your feedback! After reviewing this content, we've removed this page as part of the implementation guide revamp. https://docs.adobe.com/content/help/en/analytics/implementation/home.html

Please let us know when you run into any issues in the future!
