### ISSUE TITLE
Looks like some text isn't populating

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/analytics.en#66]
Issue in help/implement/js-implementation/event-serialization.md

see image:
![image](https://user-images.githubusercontent.com/57720744/71004048-8589fd00-20af-11ea-9fe4-26cfd9679b1d.png)

**Comment by gigazelle** [comment]
Thank you for your feedback! This issue has been fixed with the implementation guide revamp: https://docs.adobe.com/content/help/en/analytics/implementation/vars/page-vars/events/event-serialization.html
