### ISSUE TITLE
Virtual Analyst overview page not loading

### ISSUE THREAD

**Issue by woolleyadobe** [AdobeDocs/analytics.en#67]
Issue at https://docs.adobe.com/content/help/en/analytics/analyze/analysis-workspace/virtual-analyst.html

No 404, just nothing loading

**Comment by MicaPete** [comment]
@gigazelle - what did you find out about this?

**Comment by gigazelle** [comment]
This has been fixed - the correct URL is now https://docs.adobe.com/content/help/en/analytics/analyze/analysis-workspace/virtual-analyst/overview.html. Thanks!
