### ISSUE TITLE
404 page - List Props page

### ISSUE THREAD

**Issue by mboeser** [AdobeDocs/analytics.en#68]
Issue in help/implement/js-implementation/page-variables/page-variables.md

List Props link is a 404

https://docs.adobe.com/content/help/en/analytics/implementation/javascript-implementation/variables-analytics-reporting/page-variables/listprop.html

**Comment by gigazelle** [comment]
Thanks for your feedback! This has been fixed with the implementation guide revamp. https://docs.adobe.com/content/help/en/analytics/implementation/vars/page-vars/prop.html
