### ISSUE TITLE
Code on this page is incomplete.

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/analytics.en#70]
Issue in help/analyze/activity-map/activitymap-link-tracking/activitymap-start-link-tracking.md

If you follow the instructions and copy/paste the code from this page, your analytics will be broken.

**Comment by MicaPete** [comment]
@Brontojoris - since AppMeasurement.js comes bundled with ActivityMap already in it, this step in unnecessary. I will delete this documentation page.
