### ISSUE TITLE
Code is incomplete.

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/analytics.en#71]
Issue in help/analyze/activity-map/activitymap-getting-started/activitymap-getting-started-admins/activitymap-sample-implementation-code.md

This sample code is linked to from another page of documentation which explicitly states:

> We have included some *[sample implementation code](https://docs.adobe.com/content/help/en/analytics/analyze/activity-map/getting-started/get-started-admins/activitymap-enable.html)* to help you visualize the changes that have been made to the code by including the Activity Map module.

But this code is completely broken.

Also, this page says relevant code sections are bolded, but insteand it contains HTML tags instead which also breaks the javascript.

**Comment by MicaPete** [comment]
Hi - I have removed the HTML tags.
