### ISSUE TITLE
Feature request: Disable or Delete a template

### ISSUE THREAD

**Issue by john-andrilla** [AdobeDocs/analytics.en#72]
Issue in help/analyze/analysis-workspace/build-workspace-project/starter-projects.md
This page should explain how to remove a template from the list of custom templates. Currently only appears that you can create a template and share it. Unshare or remove template from broad distribution would be helpful.

**Comment by MicaPete** [comment]
I have added this to the templates documentation: 
"These templates can be created, shared, or deleted by users with admin rights or by non-admins, provided they have been granted the "Analysis Workspace: Save as Template" permission in the Admin Console. [Learn more...](https://docs.adobe.com/content/help/en/analytics/admin/admin-console/permissions/product-profile.html)
Should be published later today.
