### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/analytics.en#73]
Issue in help/implement/vars/functions/registerposttrackcallback.md

There is a note box on this page which should be updated:
> The timing and order of functions fired between registerPostTrackCallback and registerPostTrackCallback are not guaranteed. Avoid dependencies between these two functions.

It should read:
> The timing and order of functions fired between **registerPreTrackCallback** and registerPostTrackCallback are not guaranteed. Avoid dependencies between these two functions.

**Comment by gigazelle** [comment]
Perfect, thanks for pointing this out! This is fixed and will be published by tomorrow.
