### ISSUE TITLE
s.tl function link is broken

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/analytics.en#74]
Issue in help/analyze/activity-map/activitymap-link-tracking/activitymap-stl-track-custom-elements.md

s.tl() function link currently points to https://marketing.adobe.com/resources/help/en_US/sc/implement/function_tl.html which results in 404.

**Comment by gigazelle** [comment]
Thanks for pointing this out! I've fixed it, and will be published live by tomorrow.
