### ISSUE TITLE
Missing descriptions on classification's

### ISSUE THREAD

**Issue by nporter-adbe** [AdobeDocs/analytics.en#75]
Issue in help/admin/admin/mobile-management.md

There are several classification descriptions missing such as "In-App Message Online ", and "In-App Message ID". I'm unable to find descriptions for any of these dimensions anywhere else online.

**Comment by gigazelle** [comment]
Hi Nick, the Admin Console page in Analytics won't have descriptions for these classifications. I'd recommend logging an issue in the mobile services repo internal to the Adobe firewall. I'll send you an email with the repo URL.
