### ISSUE TITLE
Incorrectly formatted JSON in example code

### ISSUE THREAD

**Issue by jklockow** [AdobeDocs/analytics.en#76]
Issue in help/admin/c-data-governance/gdpr-submit-access-delete.md

![2020-02-13_13-39-01](https://user-images.githubusercontent.com/44648952/74480987-c1023700-4e66-11ea-9a7e-de14cdf89906.png)

**Comment by MicaPete** [comment]
@jklockow - thanks for submitting this. The commas have been removed and the doc page should be published by noon tomorrow.
