### ISSUE TITLE
Search does not work with some non-alphanumeric characters when fully contained within a string

### ISSUE THREAD

**Issue by inselaffe** [AdobeDocs/analytics.en#77]
https://docs.adobe.com/content/help/en/analytics/

1. Navigate to https://docs.adobe.com/content/help/en/analytics/implementation/other/hardcoded.html
2. Observe that the page contains the string "hit_source" (5th bullet point under the "Image request syntax" example)
3. In the Search input box, enter the string "hit_source" and select "Search"
4. RESULT:  no search results are returned
5. Navigate to https://docs.adobe.com/content/help/en/analytics/implementation/other/hardcoded.html
6. Observe that the page contains the string "example.sc.omtrdc.net" (2nd bullet point under the "Image request syntax" example)
7. In the Search input box, enter the string "example.sc.omtrdc.net" and select "Search"
8. RESULT:  no search results are returned

**Comment by gigazelle** [comment]
Thanks for your feedback! I have this logged with the team who manages the doc platform internally. For the time being, I would recommend using an external search engine to locate the docs you're looking for, because our internal search definitely leaves a lot to be desired. Thanks!
