### ISSUE TITLE
The link "Map your report suite to an organization ." results in a HTTP 404 error

### ISSUE THREAD

**Issue by gclausen** [AdobeDocs/analytics.en#78]
Issue in help/integrate/c-advertising-analytics/c-adanalytics-workflow/aa-provision-rs.md

On this page, https://docs.adobe.com/content/help/en/analytics/integration/advertising-analytics/advertising-analytics-workflow/aa-provision-rs.html. The link "Map your report suite to an organization ." results in a HTTP 404 error
https://marketing.adobe.com/resources/help/en_US/mcloud/map-report-suite.html does not exists (404 error)

**Comment by gigazelle** [comment]
Thanks for catching this! I've fixed it, and should be live tomorrow.
