### ISSUE TITLE
Incorrect page location for Traffic Classifications

### ISSUE THREAD

**Issue by robertsky** [AdobeDocs/analytics.en#8]
Issue in help/admin/c-traffic-management/traffic-classifications.md

This page should be under /help/admin/admin/c-traffic-variables instead?

**Comment by MicaPete** [comment]
Good point @robertsky. I will move the file and will close this issue once the change is published.

**Comment by MicaPete** [comment]
https://docs.adobe.com/content/help/en/analytics/admin/admin-tools/traffic-variables/traffic-classifications.html
