### ISSUE TITLE
X and Y Axis Correction

### ISSUE THREAD

**Issue by adobeewright** [AdobeDocs/analytics.en#83]
A Scatterplot Visualization requires at least two columns.

The fist metric defines the Y axis.
The second metric defines the X axis.
If there is a third metric available, the Scatter Visualization uses it to determine the radius of the dot.

**Comment by gigazelle** [comment]
Thanks for pointing this out! This has been corrected, and should be live this evening.

**Comment by adobeewright** [comment]
Best news today

Sent from my iPhone

On Mar 20, 2020, at 5:26 PM, Russ Whitchurch <notifications@github.com> wrote:

﻿

Thanks for pointing this out! This has been corrected, and should be live this evening.
