### ISSUE TITLE
Incomplete section

### ISSUE THREAD

**Issue by woolleyadobe** [AdobeDocs/analytics.en#85]
Issue in help/analyze/analysis-workspace/attribution-iq.md

Missing information at the bottom. Seems to cut-off mid sentence. E.g. how to change attribution model in freeform table.

**Comment by MicaPete** [comment]
@gigazelle , can you please fix this?

**Comment by gigazelle** [comment]
This appears to be resolved. @woolleyadobe, please use the github repo internal to Adobe if there are any additional issues you come across. Thanks!
