### ISSUE TITLE
Embedded video links to YouTube instead of internal MPC video.

### ISSUE THREAD

**Issue by mugdoor** [AdobeDocs/analytics.en#87]
Issue in help/analyze/analysis-workspace/analysis-workspace-features.md

Hi Guys,
Please change the embedded video on this page from the YouTube video to the MPC video. The embed code is:
https://video.tv.adobe.com/v/26266?quality=12

Thanks,
Doug

**Comment by MicaPete** [comment]
Doug, I replaced the video and it is now in the process of publishing.
