### ISSUE TITLE
getGeoCoordinates plugin source code update

### ISSUE THREAD

**Issue by gclausen** [AdobeDocs/analytics.en#88]
Issue in help/implement/vars/plugins/getgeocoordinates.md

The source code for this Analytics plugin should be updated to v1.01

/******************************************* BEGIN CODE TO DEPLOY *******************************************/
/* Adobe Consulting Plugin: getGeoCoordinates v1.01 */
s.getGeoCoordinates = function() {
    var s = {c_w:function(n,v,d) {var x=d?';expires='+d.toUTCString():'';document.cookie = n+'='+(v||'')+x+'; path=/'},c_r:function(e){e=escape(e);var t=" "+document.cookie,n=t.indexOf(" "+e+"="),a=n<0?n:t.indexOf(";",n);return"[[B]]"!=(e=n<0?"":unescape(t.substring(n+2+e.length,a<0?t.length:a)))?e:""}},
        returnValue = "",
        splitCoords = s.c_r("s_ggc").split("|"),
        options = {timeout: 5000, maximumAge: 0},

        //function to run if getting the position is successful
        success = function(position)
        {
            //get the coordinates
            var crd = position.coords,

                //create a dateObject (for expiration)
                dateObject = new Date();

            //set the dateObject to 30 minutes from now
            dateObject.setTime(dateObject.getTime() + 1800000);

            //set the "s_ggc" cookie equal to the coordinates (rounded down to 4 decimal spots, which is "accurate enough"), expiring at end of visit
            s.c_w("s_ggc", parseFloat(crd.latitude.toFixed(4)) + "|" + parseFloat(crd.longitude.toFixed(4)), dateObject);

            returnValue = "latitude=" +  parseFloat(crd.latitude.toFixed(4)) + " | longitude=" + parseFloat(crd.longitude.toFixed(4));
        },

        //function to run if getting the position produces an error
        error = function(err)
        {
            returnValue = "error retrieving geo coordinates";
        };		

    //if the "s_ggc" cookie has some legitimate values, set the return value to the latitude/longtitude
    if(splitCoords.length > 1) returnValue = "latitude=" + splitCoords[0] + " | longitude=" + splitCoords[1];

    //if we have the geolocation object, get the current coordinates within 5 seconds
    if(navigator.geolocation) navigator.geolocation.getCurrentPosition(success, error, options);

    //otherwise set the returnValue equal to "not supported"
    if(returnValue === "") returnValue = "geo coordinates not supported";

    return returnValue;
}
/******************************************** END CODE TO DEPLOY ********************************************/

**Comment by gclausen** [comment]
the above source file attachment is not minified. The below attachment has both the unminified and minified versions.
[getGeoCoordinates.txt](https://github.com/AdobeDocs/analytics.en/files/4492983/getGeoCoordinates.txt)

**Comment by gigazelle** [comment]
Hi there, I've reached out via Slack internally to continue this thread. Thanks!
