### ISSUE TITLE
The getNewRepeat plugins source needs to be updated

### ISSUE THREAD

**Issue by gclausen** [AdobeDocs/analytics.en#89]
Issue in help/implement/vars/plugins/getnewrepeat.md

[getNewRepeat.txt](https://github.com/AdobeDocs/analytics.en/files/4489880/getNewRepeat.txt)

**Comment by gclausen** [comment]
the above source file attachment is not minified. The below attachment has both the unminified and minified versions.
[getNewRepeat.txt](https://github.com/AdobeDocs/analytics.en/files/4492979/getNewRepeat.txt)

**Comment by gigazelle** [comment]
Hi there, I've reached out via Slack internally to continue this thread. Thanks!
