### ISSUE TITLE
Who has access to contribution analysis by default?

### ISSUE THREAD

**Issue by bgundersen** [AdobeDocs/analytics.en#9]
Issue in help/analyze/analysis-workspace/virtual-analyst/contribution-analysis/ca-tokens.md

Can you help clarify which users have access to contribution analysis by default. This page says you should only grant access to users who won't abuse the right, but it doesn't say whether anyone other than admins have access. John Bates should be able to answer this quickly. I'm thinking it would help to add a sentence like this: "By default, only admins have access to run contribution analyses, but you can grant access to other users by creating a permission group in [...] ."

**Comment by MicaPete** [comment]
Hi Bret - you might think I am ignoring this issue, but I am actually not :-)
I looked at this overview page and think it needs to be beefed up a lot in terms of an actual overview of the topic. So I am in the process of doing that and will publish it early next week. In the meantime, I have addressed your issue, somewhat superficially, and will close it.

**Comment by bgundersen** [comment]
Thank you!

Bret Gundersen | Director Product Management, Adobe Analytics | +1.801.360.8813 | bret@adobe.com<mailto:bret@adobe.com>
