### ISSUE TITLE
the getVisitNum source needs to be updated.

### ISSUE THREAD

**Issue by gclausen** [AdobeDocs/analytics.en#90]
Issue in help/implement/vars/plugins/getvisitnum.md

The source is attacked here.

[getVisitNum.txt](https://github.com/AdobeDocs/analytics.en/files/4489892/getVisitNum.txt)

**Comment by gclausen** [comment]
the above source file attachment is not minified. The below attachment has both the inminified and minified versions.
[getVisitNum.txt](https://github.com/AdobeDocs/analytics.en/files/4492974/getVisitNum.txt)

**Comment by gigazelle** [comment]
Hi there, I've reached out via Slack internally to continue this thread. Thanks!
