### ISSUE TITLE
the getVisitDuration plugin source needs to be updated

### ISSUE THREAD

**Issue by gclausen** [AdobeDocs/analytics.en#91]
Issue in help/implement/vars/plugins/getvisitduration.md

The source is attached here.

[getVisitDuration.txt](https://github.com/AdobeDocs/analytics.en/files/4489897/getVisitDuration.txt)

**Comment by gclausen** [comment]
the above source file attachment is not minified. The below attachment has both the unminified and minified versions.
[getVisitDuration.txt](https://github.com/AdobeDocs/analytics.en/files/4492986/getVisitDuration.txt)

**Comment by gigazelle** [comment]
Hi there, I've reached out via Slack internally to continue this thread. Thanks!
