### ISSUE TITLE
Missing graph and incomplete explanation

### ISSUE THREAD

**Issue by aliskink** [AdobeDocs/analytics.en#94]
Issue in help/components/c-variables/dimensionslist/reports-unique-visitors-v15-dsc.md

The last section references a 'graph below' which is missing.  
Also, it references applying a 'filter' to identify visitors who do/don't have a persistent cookie, but gives no explanation of how and where to find and apply this filter.  I think it refers to older versions of Analytics, or to Reports, but not Workspace, but this is unclear.

**Comment by gigazelle** [comment]
Hi Alison, a new section around unique visitors was published. You can check it out here: 
https://docs.adobe.com/content/help/en/analytics/components/metrics/unique-visitors.html
let me know your thoughts on the article, and if there are any questions about unique visitors that isn't answered there!

**Comment by aliskink** [comment]
Hi Russ,
Thanks for letting me know about this.  I don’t know how I found that other document, but the one you’ve referenced here is definitely clear and I can get to it from the ‘Adobe Analytics Documentation’ link under the Analytics help, so I’m happy with that.

Thanks
Alison



[cid:image001.jpg@01D64549.EED08360]

Alison Villazon
Implementation Analyst
.com

E: alison.villazon@marks-and-spencer.com<mailto:alison.villazon@marks-and-spencer.com>
Skype: alison.villazon@mnscorp.net<mailto:alison.villazon@mnscorp.net>
T: +4420 3882 5508
­
Marks & Spencer, Waterside House, 35 North Wharf Road, London W2 1NW
   TALK STRAIGHT • ALL IN FOR THE CUSTOMER • OWN IT AND GET IT DONE • MAKE EVERY PENNY COUNT
