### ISSUE TITLE
Unique Event Recording

### ISSUE THREAD

**Issue by aliskink** [AdobeDocs/analytics.en#97]
Issue in help/admin/admin/c-success-events/t-success-events.md

Item 9 reads "Check whether to always record the event".  This needs more information; specifically what effect does changing it to "Record once per visit" or "Use Event ID" have on the data and what changes need to be made to the tracking code, in order to make these settings work.
There should at least be a link to further information.

**Comment by gigazelle** [comment]
Hi Alison! The events overview page should have everything you need: https://docs.adobe.com/content/help/en/analytics/admin/admin-tools/success-events/success-event.html
If you need implementation instructions, particularly on how to implement events using event ID, you can see here: https://docs.adobe.com/content/help/en/analytics/implementation/vars/page-vars/events/event-serialization.html
In the future, we plan to streamline these help pages to make them more intuitive. Please let me know if these pages don't address your issue!

**Comment by aliskink** [comment]
Hi Richard,

Thanks for this.  The event-serialization page is definitely clearer.  One question that remains unexplained is whether you can apply event serialization to an ‘incrementor’ event within the s.products string, in order to prevent the amount being double-counted.
I’m particularly thinking of capturing extra data, associated with an order, after the main order-confirmation tracking has fired (in our case, we have to make a second call to interrogate the finance systems in order to return the net cost of each line-item in the order), so I only want that ‘true revenue’ to be captured once per Purchase ID, but I can’t include it in the main Purchase tracking call.

e.g. could the serialisation be set in the s.events string and the value set in the s.products string like this:

s.events = "event1:abc123";
s.products = ";prod1;1;10.99;event1=12.00";

I’m doing some experiments to see if this works, but it would be good to have it documented!

Thanks
Alison


[cid:image001.jpg@01D6454B.65A898A0]

Alison Villazon
Implementation Analyst
.com

E: alison.villazon@marks-and-spencer.com<mailto:alison.villazon@marks-and-spencer.com>
Skype: alison.villazon@mnscorp.net<mailto:alison.villazon@mnscorp.net>
T: +4420 3882 5508
­
Marks & Spencer, Waterside House, 35 North Wharf Road, London W2 1NW
   TALK STRAIGHT • ALL IN FOR THE CUSTOMER • OWN IT AND GET IT DONE • MAKE EVERY PENNY COUNT
