### ISSUE TITLE
The email address is not good. 

### ISSUE THREAD

**Issue by fred-rambert** [AdobeDocs/analytics.en#99]
the email address provided on this page: https://docs.adobe.com/content/help/en/analytics/analyze/mobapp/home.html 

is not good. 
![Screenshot 2020-05-07 at 15 19 47](https://user-images.githubusercontent.com/5792172/81299307-4ec07d80-9076-11ea-9f3a-65641c5d4f24.png)

**Comment by MicaPete** [comment]
@fred-rambert  - the correct email address is gorrepat@adobe.com.
I have corrected this in the doc and the new version will be published later this afternoon MDT.
